Repository zowe/zowe-explorer-vscode, pull requests merged in 2021-03, with the labels that each got.

#1213 Issue #992: File picker doesn't work
  packages/zowe-explorer/src/shared/actions.ts
Labels: bug

#1128 Allow multiple deletion of jobs
  packages/zowe-explorer/__mocks__/mockCreators/jobs.ts
  packages/zowe-explorer/__tests__/__unit__/job/ZoweJobNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/job/actions.unit.test.ts
  packages/zowe-explorer/i18n/sample/src/job/ZosJobsProvider.i18n.json
  packages/zowe-explorer/i18n/sample/src/job/actions.i18n.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/src/extension.ts
  packages/zowe-explorer/src/job/ZosJobsProvider.ts
  packages/zowe-explorer/src/job/actions.ts
Labels: 21PI1, Jobs, Sprint 1

#1218 issue 1127: Pre-select existing reject unauthorized value for update profile
  packages/zowe-explorer/i18n/sample/src/Profiles.i18n.json
  packages/zowe-explorer/src/Profiles.ts
Labels: 21PI1, Profiles, Sprint 3, bug

#1235 zFTP ReadMe and Changeloe update
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/README.md
Labels: docs

#1231 Bug fix to prompt for creds when issuing MVS command
  packages/zowe-explorer/src/command/MvsCommandHandler.ts
Labels: 21PI1, Sprint 3

#1230 Issue MVS Refinements
  packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
  packages/zowe-explorer/i18n/sample/package.i18n.json
  packages/zowe-explorer/i18n/sample/src/command/MvsCommandHandler.i18n.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/package.nls.json
  packages/zowe-explorer/src/command/MvsCommandHandler.ts
  packages/zowe-explorer/src/extension.ts
  packages/zowe-explorer/src/globals.ts
Labels: 21PI1, Sprint 3, Technical Debt
