Repository zowe/zowe-explorer-vscode, pull requests merged in 2021-09, with the labels that each got.

#1383 Standardize view IDs per upcoming extenders documentation
  docs/Early Access - Changes Affecting Extenders.md
  docs/README-Extending.md
  packages/zowe-explorer/__tests__/__theia__/theia/Locators.ts
  packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
  packages/zowe-explorer/i18n/sample/package.i18n.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/package.nls.json
  packages/zowe-explorer/src/dataset/DatasetTree.ts
  packages/zowe-explorer/src/job/ZosJobsProvider.ts
Labels: vNext

#1467 Documentation for imperative logger for extenders
  docs/extenders/Error Handling.md
Labels: docs

#1443 validate profile and credential
  packages/zowe-explorer-ftp-extension/src/ZoweExplorerAbstractFtpApi.ts
Labels: zFTP

#1448 [next] Extender load on registration
  package.json
  packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
  packages/zowe-explorer-api/src/profiles/ZoweExplorerApi.ts
  packages/zowe-explorer-ftp-extension/src/extension.ts
  packages/zowe-explorer/__tests__/__unit__/job/ZoweJobNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/uss/USSTree.unit.test.ts
  packages/zowe-explorer/src/Profiles.ts
  packages/zowe-explorer/src/ZoweExplorerExtender.ts
  packages/zowe-explorer/src/dataset/DatasetTree.ts
  packages/zowe-explorer/src/extension.ts
  packages/zowe-explorer/src/job/ZosJobsProvider.ts
  packages/zowe-explorer/src/uss/USSTree.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
  yarn.lock
Labels: vNext

#1437 [next] (Doc) Update the profile config doc
  docs/Early Access - Using Global Profile Configuration.md
Labels: docs, vNext

#1439 [next] Add support for project level config
  packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
  packages/zowe-explorer/package.json
  packages/zowe-explorer/src/Profiles.ts
  packages/zowe-explorer/src/extension.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
  yarn.lock
Labels: vNext

#1471 [next] Refactor for SDK compatibility
  .github/workflows/zowe-explorer-ci.yml
  .vscode/launch.json
  package.json
  packages/zowe-explorer-api/src/profiles/ZoweExplorerZosmfApi.ts
  packages/zowe-explorer/__mocks__/@zowe/cli.ts
  packages/zowe-explorer/__mocks__/@zowe/imperative.ts
  packages/zowe-explorer/__mocks__/mockCreators/shared.ts
  packages/zowe-explorer/__tests__/__integration__/DatasetTree.integration.test.ts
  packages/zowe-explorer/__tests__/__integration__/USSTree.integration.test.ts
  packages/zowe-explorer/__tests__/__integration__/ZoweNode.integration.test.ts
  packages/zowe-explorer/__tests__/__integration__/ZoweUSSNode.integration.test.ts
  packages/zowe-explorer/__tests__/__integration__/command/mvsCommands.integration.test.ts
  packages/zowe-explorer/__tests__/__integration__/command/tsoCommands.integration.test.ts
  packages/zowe-explorer/__tests__/__integration__/dataset/actions.integration.test.ts
  packages/zowe-explorer/__tests__/__integration__/extension.integration.test.ts
  packages/zowe-explorer/__tests__/__integration__/shared/refresh.integration.test.ts
  packages/zowe-explorer/__tests__/__integration__/uss/ussNodeActions.integration.test.ts
  packages/zowe-explorer/__tests__/__unit__/Profiles.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/dataset/actions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/dataset/dsNodeActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/job/ZoweJobNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/job/actions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/uss/USSTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/uss/ZoweUSSNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/profileLink.unit.test.ts
  packages/zowe-explorer/src/Profiles.ts
  packages/zowe-explorer/src/ZoweExplorerExtender.ts
  yarn.lock
Labels: vNext

#1483 Fix Multi-Delete Bug
  packages/zowe-explorer/__tests__/__unit__/dataset/actions.unit.test.ts
  packages/zowe-explorer/i18n/sample/package.i18n.json
  packages/zowe-explorer/i18n/sample/src/dataset/actions.i18n.json
  packages/zowe-explorer/package.nls.json
  packages/zowe-explorer/src/dataset/actions.ts
  packages/zowe-explorer/src/extension.ts
Labels: bug, Priority: High

#1491 Fix Theia GHA tests by using the supported version 1.15.0
  .github/workflows/theia-zowe-explorer-ci.yml
Labels: docs, Technical Debt

#1478 Issue #1297: Changing name of command window for TSO/MVS commands
  packages/zowe-explorer/__tests__/__integration__/command/mvsCommands.integration.test.ts
  packages/zowe-explorer/__tests__/__integration__/command/tsoCommands.integration.test.ts
  packages/zowe-explorer/i18n/sample/src/abstract/ZoweCommandProvider.i18n.json
  packages/zowe-explorer/i18n/sample/src/command/MvsCommandHandler.i18n.json
  packages/zowe-explorer/i18n/sample/src/command/TsoCommandHandler.i18n.json
  packages/zowe-explorer/src/abstract/ZoweCommandProvider.ts
  packages/zowe-explorer/src/command/MvsCommandHandler.ts
  packages/zowe-explorer/src/command/TsoCommandHandler.ts
Labels: enhancement, backlog

#1479 Issue #1297: Fixed bug when cancelling TSO command
  packages/zowe-explorer/src/command/TsoCommandHandler.ts
Labels: backlog

#1486 Check Credentials error disappearing too quickly bug fix
  packages/zowe-explorer/__tests__/__unit__/utils.unit.test.ts
  packages/zowe-explorer/i18n/sample/src/Profiles.i18n.json
  packages/zowe-explorer/i18n/sample/src/dataset/DatasetTree.i18n.json
  packages/zowe-explorer/i18n/sample/src/dataset/ZoweDatasetNode.i18n.json
  packages/zowe-explorer/i18n/sample/src/utils/ProfilesUtils.i18n.json
  packages/zowe-explorer/src/Profiles.ts
  packages/zowe-explorer/src/dataset/DatasetTree.ts
  packages/zowe-explorer/src/dataset/ZoweDatasetNode.ts
  packages/zowe-explorer/src/dataset/actions.ts
  packages/zowe-explorer/src/extension.ts
  packages/zowe-explorer/src/job/actions.ts
  packages/zowe-explorer/src/uss/USSTree.ts
  packages/zowe-explorer/src/uss/actions.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
  packages/zowe-explorer/src/utils/TempFolder.ts
Labels: bug

#1501 (Docs) Update Readme and Changelog for 1.19.0
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/README.md
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/README.md
Labels: docs

#1473 [next] Error handling and User/Pass Prompting for Config File Profiles
  packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
  packages/zowe-explorer/__tests__/__unit__/Profiles.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils.unit.test.ts
  packages/zowe-explorer/i18n/sample/src/Profiles.i18n.json
  packages/zowe-explorer/src/Profiles.ts
  packages/zowe-explorer/src/ZoweExplorerExtender.ts
  packages/zowe-explorer/src/dataset/actions.ts
  packages/zowe-explorer/src/extension.ts
  packages/zowe-explorer/src/job/actions.ts
  packages/zowe-explorer/src/uss/USSTree.ts
  packages/zowe-explorer/src/uss/actions.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
  packages/zowe-explorer/src/utils/TempFolder.ts
Labels: vNext
