Repository zowe/zowe-explorer-vscode, pull requests merged in 2021-08, with the labels that each got.

#1426 Bug Fix: Create/Update Profile Esc Error on Host Input
  package.json
  packages/zowe-explorer/__tests__/__integration__/Profiles.integration.test.ts
  packages/zowe-explorer/__tests__/__unit__/Profiles.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/i18n/sample/src/Profiles.i18n.json
  packages/zowe-explorer/src/Profiles.ts
  packages/zowe-explorer/src/abstract/ZoweTreeProvider.ts
  yarn.lock
Labels: bug

#1436 (Doc) Update 1.18.0 Readme and Changelog
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/README.md
Labels: docs

#1446 Reminder added to PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: Technical Debt

#1430 Integration test improvements
  .vscode/launch.json
  .vscode/tasks.json
  README.md
  docs/README-Developer.md
  packages/zowe-explorer/__tests__/__integration__/extension.integration.test.ts
  packages/zowe-explorer/package.json
  packages/zowe-explorer/scripts/createDemoNodes.ts
  packages/zowe-explorer/src/dataset/actions.ts
  scripts/systemTestEnv.ts
Labels: enhancement, backlog, Technical Debt, Tests

#1451 (Docs) Update Readme and Changelog for 1.18.1
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/README.md
Labels: docs

#1435 [next] Refactor ProfilesCache & Update with changes from master branch
  .github/actions/common.js
  .github/actions/deploy-npm-package/action.yml
  .github/actions/deploy-npm-package/index.js
  .github/actions/deploy-vscode-extension/action.yml
  .github/actions/deploy-vscode-extension/index.js
  .github/workflows/deployment.yml
  docs/README-Extending.md
  docs/developer/Menu-Commands.md
  package.json
  packages/zowe-explorer-api/src/index.ts
  packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
  packages/zowe-explorer-api/src/profiles/ProfilesConfig.ts
  packages/zowe-explorer-api/src/profiles/ZoweExplorerApi.ts
  packages/zowe-explorer-api/src/profiles/ZoweExplorerZosmfApi.ts
  packages/zowe-explorer-api/src/profiles/index.ts
  packages/zowe-explorer-api/src/security/KeytarCredentialManager.ts
  packages/zowe-explorer-api/tsconfig.json
  packages/zowe-explorer-ftp-extension/src/extension.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/README.md
  packages/zowe-explorer/__tests__/__integration__/Profiles.integration.test.ts
  packages/zowe-explorer/__tests__/__unit__/Profiles.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/ZoweExplorerExtender.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/api/ZoweExplorerApiRegister.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/command/tsoCommandHandler.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/shared/utils.unit.test.ts
  packages/zowe-explorer/i18n/sample/src/Profiles.i18n.json
  packages/zowe-explorer/i18n/sample/src/extension.i18n.json
  packages/zowe-explorer/src/Profiles.ts
  packages/zowe-explorer/src/ZoweExplorerExtender.ts
  packages/zowe-explorer/src/abstract/ZoweTreeProvider.ts
  packages/zowe-explorer/src/command/TsoCommandHandler.ts
  packages/zowe-explorer/src/extension.ts
  packages/zowe-explorer/src/shared/actions.ts
  packages/zowe-explorer/src/shared/refresh.ts
  packages/zowe-explorer/src/uss/ZoweUSSNode.ts
  packages/zowe-explorer/src/uss/actions.ts
  yarn.lock
Labels: vNext
