Repository zowe/zowe-explorer-vscode, pull requests merged in 2021-07, with the labels that each got.

#1347 Support multiple VS Code windows for files opened via Zowe Explorer
  packages/zowe-explorer/__tests__/__integration__/ZoweUSSNode.integration.test.ts
  packages/zowe-explorer/__tests__/__integration__/extension.integration.test.ts
  packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
  packages/zowe-explorer/i18n/sample/package.i18n.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/package.nls.json
  packages/zowe-explorer/src/extension.ts
  packages/zowe-explorer/src/utils/TempFolder.ts
  scripts/systemTestEnv.ts
Labels: Priority: High, bug, docs

#1386 Issue #1206: automatically add missing job profile
  packages/zowe-explorer/__mocks__/mockCreators/jobs.ts
  packages/zowe-explorer/__tests__/__unit__/job/actions.unit.test.ts
  packages/zowe-explorer/src/extension.ts
  packages/zowe-explorer/src/job/actions.ts
Labels: enhancement

#1384 Extender documentation for the KeytarApi for SCS
  docs/extenders/SecureCredentials.md
Labels: docs

#1372 Update documentation to match new delete-multiple feature
  docs/images/ZE-delete-ds2.gif
  packages/zowe-explorer/README.md
Labels: docs, enhancement

#1398 (Doc) Update the 1.17.0 Readme and Changelog
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/README.md
Labels: docs
