Repository zowe/zowe-explorer-vscode, pull requests merged in 2021-02, with the labels that each got.

#1178 PR #1120 linked issue: Always allow prompting
  packages/zowe-explorer/__tests__/__unit__/Profiles.unit.test.ts
  packages/zowe-explorer/src/Profiles.ts
  packages/zowe-explorer/src/abstract/ZoweTreeProvider.ts
Labels: 21PI1, Profiles, bug

#1151 Fix issue 1144: Persist removed favorite profiles between sessions
  packages/zowe-explorer/__tests__/__unit__/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/job/ZosJobsProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/uss/USSTree.unit.test.ts
  packages/zowe-explorer/src/dataset/DatasetTree.ts
  packages/zowe-explorer/src/job/ZosJobsProvider.ts
  packages/zowe-explorer/src/uss/USSTree.ts
Labels: 21PI1

#1120 Multiple issues: Fixed errors with updating optional profile fields
  packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
  packages/zowe-explorer-api/src/tree/IZoweTree.ts
  packages/zowe-explorer/__tests__/__unit__/KeytarCredentialManager.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/Profiles.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/abstract/TreeProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/src/KeytarCredentialManager.ts
  packages/zowe-explorer/src/Profiles.ts
  packages/zowe-explorer/src/abstract/ZoweTreeProvider.ts
  packages/zowe-explorer/src/extension.ts
  packages/zowe-explorer/src/uss/USSTree.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
Labels: 21PI1, Profiles, bug

#1157 HOT FIX: Added fixes for the profiles error on issue 1147
  packages/zowe-explorer/__tests__/__unit__/shared/utils.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/uss/ZoweUSSNode.unit.test.ts
  packages/zowe-explorer/src/dataset/DatasetTree.ts
  packages/zowe-explorer/src/shared/utils.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
Labels: 21PI1

#1150 Issue #1147: Fix repeat prompting
  packages/zowe-explorer/__tests__/__unit__/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/job/ZosJobsProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/uss/USSTree.unit.test.ts
  packages/zowe-explorer/i18n/sample/src/dataset/DatasetTree.i18n.json
  packages/zowe-explorer/i18n/sample/src/job/ZosJobsProvider.i18n.json
  packages/zowe-explorer/i18n/sample/src/job/ZoweJobNode.i18n.json
  packages/zowe-explorer/i18n/sample/src/uss/USSTree.i18n.json
  packages/zowe-explorer/src/Profiles.ts
  packages/zowe-explorer/src/abstract/ZoweTreeProvider.ts
  packages/zowe-explorer/src/dataset/DatasetTree.ts
  packages/zowe-explorer/src/job/ZosJobsProvider.ts
  packages/zowe-explorer/src/job/ZoweJobNode.ts
  packages/zowe-explorer/src/uss/USSTree.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
Labels: 21PI1, Security, bug

#1177 Update documentation in package
  README.md
  docs/images/ZE-allocate.gif
  docs/images/ZE-copy-member.gif
  docs/images/ZE-cre-pds-member.gif
  docs/images/ZE-delete-ds.gif
  docs/images/ZE-edit-upload.gif
  docs/images/ZE-set-params.gif
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/README.md
Labels: 21PI1

#1183 Issue:1013 Add beforeMemberName to textbox for pasteMember()
  packages/zowe-explorer/src/dataset/actions.ts
Labels: 21PI1, Datasets, Sprint 1

#1211 issue 1190: Prompted vs APIML login
  packages/zowe-explorer/src/Profiles.ts
Labels: 21PI1

#1212 Issue 1210: Member filter refinement
  packages/zowe-explorer/i18n/sample/src/Profiles.i18n.json
  packages/zowe-explorer/src/dataset/DatasetTree.ts
Labels: 21PI1, Sprint 1, bug
