Repository zowe/zowe-explorer-vscode, pull requests merged in 2021-04, with the labels that each got.

#1252 enable zftp Jes functions and optimize some code
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer-ftp-extension/src/ZoweExplorerAbstractFtpApi.ts
  packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpJesApi.ts
  packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpMvsApi.ts
  packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpUssApi.ts
  packages/zowe-explorer-ftp-extension/src/extension.ts
  yarn.lock
Labels: 21PI1

#1259 Issue #650 partial fix: USS tree collapses after folder rename
  packages/zowe-explorer-api/src/tree/IZoweTreeNode.ts
  packages/zowe-explorer/__tests__/__unit__/uss/USSTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/uss/ZoweUSSNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/uss/actions.unit.test.ts
  packages/zowe-explorer/i18n/sample/src/uss/USSTree.i18n.json
  packages/zowe-explorer/i18n/sample/src/uss/actions.i18n.json
  packages/zowe-explorer/src/shared/context.ts
  packages/zowe-explorer/src/shared/utils.ts
  packages/zowe-explorer/src/uss/USSTree.ts
  packages/zowe-explorer/src/uss/ZoweUSSNode.ts
  packages/zowe-explorer/src/uss/actions.ts
Labels: 21PI1

#1253 Issue #969: Jobs with a hash in the name can't be opened
  packages/zowe-explorer/__tests__/__unit__/SpoolProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/job/actions.unit.test.ts
  packages/zowe-explorer/src/SpoolProvider.ts
Labels: 21PI1

#1267 1.14 doc update
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/README.md
Labels: docs

#1277 Update README with more information about Theia tests
  docs/Developer's ReadMe.md
Labels: Tests, Theia, docs
