Repository zowe/zowe-explorer-vscode, pull requests merged in 2021-06, with the labels that each got.

#1322 Integration test for allocate like
  package.json
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__integration__/extension.integration.test.ts
  packages/zowe-explorer/package.json
  packages/zowe-explorer/src/dataset/actions.ts
  scripts/systemTestEnv.ts
  yarn.lock
Labels: Technical Debt, Tests

#1343 Allow refresh for dataset member names
  packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
  packages/zowe-explorer/i18n/sample/package.i18n.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/package.nls.json
  packages/zowe-explorer/src/dataset/actions.ts
  packages/zowe-explorer/src/extension.ts
  packages/zowe-explorer/src/globals.ts
Labels: docs

#1353 (1.16.0, Docs) Update the ZE and zFTP Readmes and Changelogs
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/README.md
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/README.md
Labels: docs

#1323 Multiple delete of datasets/members
  packages/zowe-explorer/__mocks__/mockCreators/datasets.ts
  packages/zowe-explorer/__mocks__/mockCreators/shared.ts
  packages/zowe-explorer/__mocks__/vscode.ts
  packages/zowe-explorer/__tests__/__integration__/dataset/actions.integration.test.ts
  packages/zowe-explorer/__tests__/__integration__/extension.integration.test.ts
  packages/zowe-explorer/__tests__/__integration__/shared/refresh.integration.test.ts
  packages/zowe-explorer/__tests__/__unit__/dataset/actions.unit.test.ts
  packages/zowe-explorer/i18n/sample/src/dataset/actions.i18n.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/src/dataset/DatasetTree.ts
  packages/zowe-explorer/src/dataset/actions.ts
  packages/zowe-explorer/src/extension.ts
Labels: Datasets, UX, backlog, enhancement, in progress

#1363 Issue #988: update job logs ability
  packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/job/actions.unit.test.ts
  packages/zowe-explorer/i18n/sample/package.i18n.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/package.nls.json
  packages/zowe-explorer/src/SpoolProvider.ts
  packages/zowe-explorer/src/extension.ts
  packages/zowe-explorer/src/globals.ts
  packages/zowe-explorer/src/job/ZoweJobNode.ts
  packages/zowe-explorer/src/job/actions.ts
Labels: Jobs, enhancement
