Repository zowe/zowe-explorer-vscode, pull requests merged in 2022-01, with the labels that each got.

#1623 [next] login/logout extensibility
  packages/zowe-explorer/__tests__/__unit__/Profiles.unit.test.ts
  packages/zowe-explorer/i18n/sample/src/Profiles.i18n.json
  packages/zowe-explorer/i18n/sample/src/job/actions.i18n.json
  packages/zowe-explorer/src/Profiles.ts
  packages/zowe-explorer/src/extension.ts
Labels: vNext

#1629 [next] Config file creation to include extenders/CLI installation dependency removed
  package.json
  packages/zowe-explorer/i18n/sample/src/Profiles.i18n.json
  packages/zowe-explorer/src/Profiles.ts
  packages/zowe-explorer/src/ZoweExplorerExtender.ts
  packages/zowe-explorer/src/globals.ts
  yarn.lock
Labels: vNext

#1640 Update READMEs and GHA to Node 12 or later
  .github/workflows/zowe-explorer-ci.yml
  .github/workflows/zowe-explorer-ftp-ci.yml
  README.md
  packages/zowe-explorer/README.md
Labels: docs, Security

#1643 (Doc) Add Theia note
  packages/zowe-explorer/README.md
Labels: docs
