Repository zowe/zowe-explorer-vscode, pull requests merged in 2023-06, with the labels that each got.

#2230 Add support for custom credential manager extensions
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__mocks__/@zowe/imperative.ts
  packages/zowe-explorer/__tests__/__unit__/Profiles.extended.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/globals.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/shared/init.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
  packages/zowe-explorer/i18n/sample/src/utils/ProfilesUtils.i18n.json
  packages/zowe-explorer/src/ZoweExplorerExtender.ts
  packages/zowe-explorer/src/globals.ts
  packages/zowe-explorer/src/shared/init.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
Labels: dev-docs

#2319 [vNext] Change activation event to onStartupFinished
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/package.json
Labels: v3

#2340 Install known good version of Lerna in deployment workflow
  .github/workflows/deployment.yml
Labels: no-changelog

#2341 [vNext] Merge 2.9.0 changes from main
  .github/workflows/deployment.yml
  lerna.json
  packages/eslint-plugin-zowe-explorer/CHANGELOG.md
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/src/globals/index.ts
  packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
  packages/zowe-explorer-api/src/profiles/UserSettings.ts
  packages/zowe-explorer-api/src/tree/IZoweTree.ts
  packages/zowe-explorer-api/src/vscode/ZoweVsCodeExtension.ts
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/__tests__/__unit__/FtpApi/ZoweExplorerAbstractFtpApi.unit.test.ts
  packages/zowe-explorer-ftp-extension/src/ZoweExplorerAbstractFtpApi.ts
  packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpMvsApi.ts
  packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpUssApi.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__mocks__/@zowe/imperative.ts
  packages/zowe-explorer/__mocks__/mockCreators/datasets.ts
  packages/zowe-explorer/__tests__/__unit__/PersistentFilters.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/SpoolProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/ZoweNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/dataset/actions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/globals.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/shared/init.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/uss/__snapshots__/ZoweUSSNode.unit.test.ts.snap
  packages/zowe-explorer/__tests__/__unit__/uss/actions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
  packages/zowe-explorer/i18n/sample/src/dataset/actions.i18n.json
  packages/zowe-explorer/i18n/sample/src/shared/utils.i18n.json
  packages/zowe-explorer/i18n/sample/src/uss/actions.i18n.json
  packages/zowe-explorer/i18n/sample/src/utils/ProfilesUtils.i18n.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/src/PersistentFilters.ts
  packages/zowe-explorer/src/SpoolProvider.ts
  packages/zowe-explorer/src/ZoweExplorerExtender.ts
  packages/zowe-explorer/src/dataset/DatasetTree.ts
  packages/zowe-explorer/src/dataset/ZoweDatasetNode.ts
  packages/zowe-explorer/src/dataset/actions.ts
  packages/zowe-explorer/src/globals.ts
  packages/zowe-explorer/src/job/ZosJobsProvider.ts
  packages/zowe-explorer/src/job/ZoweJobNode.ts
  packages/zowe-explorer/src/shared/context.ts
  packages/zowe-explorer/src/shared/init.ts
  packages/zowe-explorer/src/shared/utils.ts
  packages/zowe-explorer/src/uss/USSTree.ts
  packages/zowe-explorer/src/uss/ZoweUSSNode.ts
  packages/zowe-explorer/src/uss/actions.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
  yarn.lock
Labels: no-changelog

#2352 fix(dep): bump semver to 7.5.3 to resolve audit
  package.json
  packages/zowe-explorer-api/package.json
  yarn.lock
Labels: no-changelog

#2355 Updates to ZE README
  packages/zowe-explorer/README.md
Labels: no-changelog

#2354 2.9.1 Release
  lerna.json
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer/CHANGELOG.md
Labels: no-changelog
