Repository zowe/zowe-explorer-vscode, pull requests merged in 2024-11, with the labels that each got.

#3292 fix(v3): Pass `responseTimeout` in z/OSMF MVS and USS API calls
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/profiles/ZoweExplorerZosmfApi.unit.test.ts
  packages/zowe-explorer-api/src/profiles/ZoweExplorerZosmfApi.ts
  packages/zowe-explorer/__tests__/__unit__/extending/ZoweExplorerZosmfApi.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/extending/__snapshots__/ZoweExplorerZosmfApi.unit.test.ts.snap
Labels: size/L

#3272 Remove inconsistency in translation strings
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/src/vscode/ZoweVsCodeExtension.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/commands/MvsCommandHandler.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/commands/TsoCommandHandler.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/commands/UnixCommandHandler.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/management/ProfileManagement.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetActions.extended.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/CertificateWizard.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/package.nls.json
  packages/zowe-explorer/src/commands/MvsCommandHandler.ts
  packages/zowe-explorer/src/commands/TsoCommandHandler.ts
  packages/zowe-explorer/src/commands/UnixCommandHandler.ts
  packages/zowe-explorer/src/configuration/Profiles.ts
  packages/zowe-explorer/src/management/ProfileManagement.ts
  packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTemplates.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
  packages/zowe-explorer/src/trees/job/JobActions.ts
  packages/zowe-explorer/src/trees/job/JobTree.ts
  packages/zowe-explorer/src/trees/uss/USSActions.ts
  packages/zowe-explorer/src/utils/AuthUtils.ts
  packages/zowe-explorer/src/utils/CertificateWizard.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
  packages/zowe-explorer/src/webviews/src/edit-attributes/App.tsx
Labels: size/XL

#3288 refactor: Adjust "Add to Workspace" labels and fetch resources for external URLs
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedUtils.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/UriHandler.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/trees/shared/SharedUtils.ts
  packages/zowe-explorer/src/trees/uss/USSTree.ts
  packages/zowe-explorer/src/utils/UriHandler.ts
Labels: no-changelog, size/M

#3297 Change default credentials manager check and not-found dialog
  .vscode/launch.json
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
Labels: size/L

#3302 fix: Prompt for credentials when 401 in editor, fix profile propagation
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/tree/ZoweTreeNode.unit.test.ts
  packages/zowe-explorer-api/src/tree/ZoweTreeNode.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__integration__/bdd/step_definitions/dialogs/ShowConfigErrorDialog.steps.ts
  packages/zowe-explorer/__tests__/__integration__/bdd/step_definitions/profiles/UpdateCredentials.steps.ts
  packages/zowe-explorer/__tests__/__mocks__/mockCreators/shared.ts
  packages/zowe-explorer/__tests__/__unit__/commands/ZoweCommandProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/ZoweTreeProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/ZoweJobNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/UssFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/ZoweUSSNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/AuthUtils.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/commands/ZoweCommandProvider.ts
  packages/zowe-explorer/src/configuration/Profiles.ts
  packages/zowe-explorer/src/trees/ZoweTreeProvider.ts
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
  packages/zowe-explorer/src/trees/job/JobFSProvider.ts
  packages/zowe-explorer/src/trees/uss/UssFSProvider.ts
  packages/zowe-explorer/src/utils/AuthUtils.ts
Labels: size/XL

#3315 fix: Propagate rename to PDS members
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
Labels: size/M

#3312 Fix Coverity code smells in V3
  packages/zowe-explorer-api/src/fs/BaseProvider.ts
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
  packages/zowe-explorer/src/trees/uss/UssFSProvider.ts
Labels: no-changelog, size/S

#3316 Change Authentication Msg
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/configuration/Profiles.ts
Labels: size/M

#3318 fix(3.0.3): Prompt in editor for 401 error, fix profile propagation
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/tree/ZoweTreeNode.unit.test.ts
  packages/zowe-explorer-api/src/tree/ZoweTreeNode.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/ZoweJobNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/UssFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/AuthUtils.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
  packages/zowe-explorer/src/trees/job/JobFSProvider.ts
  packages/zowe-explorer/src/trees/uss/UssFSProvider.ts
  packages/zowe-explorer/src/utils/AuthUtils.ts
Labels: size/L

#3313 fix(ftp): Generate member name if missing in `putContents`
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/__tests__/__unit__/Mvs/ZoweExplorerFtpMvsApi.unit.test.ts
  packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpMvsApi.ts
Labels: size/M

#3321 Fix infinite loop when fetching USS resources with stat()
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/src/trees/uss/UssFSProvider.ts
Labels: size/XS

#3301 Port fixes from main for 3.0.3
  .vscode/launch.json
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/profiles/ZoweExplorerZosmfApi.unit.test.ts
  packages/zowe-explorer-api/__tests__/__unit__/tree/ZoweTreeNode.unit.test.ts
  packages/zowe-explorer-api/src/profiles/ZoweExplorerZosmfApi.ts
  packages/zowe-explorer-api/src/tree/ZoweTreeNode.ts
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/__tests__/__unit__/Mvs/ZoweExplorerFtpMvsApi.unit.test.ts
  packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpMvsApi.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__integration__/bdd/features/dialogs/ShowConfigErrorDialog.feature
  packages/zowe-explorer/__tests__/__integration__/bdd/step_definitions/dialogs/ShowConfigErrorDialog.steps.ts
  packages/zowe-explorer/__tests__/__integration__/bdd/step_definitions/profiles/UpdateCredentials.steps.ts
  packages/zowe-explorer/__tests__/__integration__/bdd/wdio.conf.ts
  packages/zowe-explorer/__tests__/__mocks__/vscode.ts
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/extending/ZoweExplorerZosmfApi.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/extending/__snapshots__/ZoweExplorerZosmfApi.unit.test.ts.snap
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetInit.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/ZoweJobNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/UssFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/ZoweUSSNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/AuthUtils.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/configuration/Profiles.ts
  packages/zowe-explorer/src/extension.ts
  packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
  packages/zowe-explorer/src/trees/dataset/DatasetInit.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
  packages/zowe-explorer/src/trees/job/JobFSProvider.ts
  packages/zowe-explorer/src/trees/job/JobTree.ts
  packages/zowe-explorer/src/trees/uss/USSTree.ts
  packages/zowe-explorer/src/trees/uss/UssFSProvider.ts
  packages/zowe-explorer/src/trees/uss/ZoweUSSNode.ts
  packages/zowe-explorer/src/utils/AuthUtils.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
Labels: size/XXL

#3317 Prepare 3.0.3 release
  lerna.json
  packages/eslint-plugin-zowe-explorer/CHANGELOG.md
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer/CHANGELOG.md
  pnpm-lock.yaml
Labels: no-changelog, size/M

#3296 Update profile watchers and utilities to use Zowe SDK enhancements
  package.json
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/fs/BaseProvider.unit.test.ts
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-api/src/utils/ErrorCorrelator.ts
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__mocks__/@zowe/imperative.ts
  packages/zowe-explorer/__tests__/__mocks__/mockCreators/profiles.ts
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/extending/ZoweExplorerExtender.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedInit.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/src/configuration/Constants.ts
  packages/zowe-explorer/src/configuration/SettingsConfig.ts
  packages/zowe-explorer/src/extending/ZoweExplorerExtender.ts
  packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
  packages/zowe-explorer/src/trees/dataset/DatasetInit.ts
  packages/zowe-explorer/src/trees/shared/SharedInit.ts
  packages/zowe-explorer/src/trees/shared/SharedUtils.ts
  packages/zowe-explorer/src/trees/uss/USSActions.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
  pnpm-lock.yaml
Labels: size/XXL

#3325 feat: Support multi-select for "Add to Workspace" feature
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedUtils.unit.test.ts
  packages/zowe-explorer/src/trees/shared/SharedUtils.ts
Labels: size/M

#3322 Fix flaky integration tests and error handling for invalid team config
  .github/workflows/zowe-explorer-ci.yml
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer/.prettierignore
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__common__/base.wdio.conf.ts
  packages/zowe-explorer/__tests__/__e2e__/step_definitions/list/ListTreeItems.steps.ts
  packages/zowe-explorer/__tests__/__e2e__/wdio.conf.ts
  packages/zowe-explorer/__tests__/__integration__/bdd/features/dialogs/AddConfigQuickPick.feature
  packages/zowe-explorer/__tests__/__integration__/bdd/features/profiles/UpdateCredentials.feature
  packages/zowe-explorer/__tests__/__integration__/bdd/resources/ShowConfigErrorDialog/zowe.config.json
  packages/zowe-explorer/__tests__/__integration__/bdd/resources/UpdateCredentials/zowe.config.json
  packages/zowe-explorer/__tests__/__integration__/bdd/step_definitions/dialogs/AddConfigQuickPick.steps.ts
  packages/zowe-explorer/__tests__/__integration__/bdd/step_definitions/profiles/UpdateCredentials.steps.ts
  packages/zowe-explorer/__tests__/__integration__/bdd/wdio.conf.ts
  packages/zowe-explorer/__tests__/__pageobjects__/QuickPick.ts
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedUtils.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
  packages/zowe-explorer/src/configuration/Profiles.ts
  packages/zowe-explorer/src/trees/ZoweTreeProvider.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
Labels: size/L

#3334 Update changelogs after 3.0.3
  packages/eslint-plugin-zowe-explorer/CHANGELOG.md
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer/CHANGELOG.md
Labels: size/M

#3309 Add type to session nodes
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSTree.unit.test.ts
  packages/zowe-explorer/src/configuration/Constants.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
  packages/zowe-explorer/src/trees/job/JobTree.ts
  packages/zowe-explorer/src/trees/uss/USSTree.ts
Labels: size/M

#3319 fix: formatting of 401 error message
  packages/zowe-explorer/__tests__/__unit__/utils/AuthUtils.unit.test.ts
  packages/zowe-explorer/src/utils/AuthUtils.ts
Labels: no-changelog, size/S

#3299 feat: Expose local storage through access control facility
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/src/extend/IApiExplorerExtender.ts
  packages/zowe-explorer-api/src/extend/ILocalStorageAccess.ts
  packages/zowe-explorer-api/src/extend/index.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/commands/MvsCommandHandler.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/commands/TsoCommandHandler.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/commands/UnixCommandHandler.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/configuration/SettingsConfig.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/extending/ZoweExplorerExtender.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/icons/Icon.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/tools/ZoweLocalStorage.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/tools/ZowePersistentFilters.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/tools/ZoweSaveQueue.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/ZoweTreeProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobInit.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/ZoweJobNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedHistoryView.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/ZoweUSSNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/LoggerUtils.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/TreeViewUtils.unit.test.ts
  packages/zowe-explorer/src/configuration/SettingsConfig.ts
  packages/zowe-explorer/src/extending/ZoweExplorerExtender.ts
  packages/zowe-explorer/src/extension.ts
  packages/zowe-explorer/src/tools/ZoweLocalStorage.ts
Labels: size/L

#3328 fix(v2): Show error for unsaved data set rename
  package.json
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/TreeViewUtils.unit.test.ts
  packages/zowe-explorer/src/dataset/DatasetTree.ts
  packages/zowe-explorer/src/uss/USSTree.ts
  packages/zowe-explorer/src/utils/TreeViewUtils.ts
  yarn.lock
Labels: size/XL

#3291 VSC Proxy Support
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__mocks__/vscode.ts
  packages/zowe-explorer-api/__tests__/__unit__/profiles/ProfilesCache.unit.test.ts
  packages/zowe-explorer-api/__tests__/__unit__/profiles/ZoweExplorerZosmfApi.unit.test.ts
  packages/zowe-explorer-api/__tests__/__unit__/profiles/__snapshots__/ZoweExplorerZosmfApi.unit.test.ts.snap
  packages/zowe-explorer-api/__tests__/__unit__/vscode/doc/VscSettings.unit.test.ts
  packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
  packages/zowe-explorer-api/src/profiles/ZoweExplorerZosmfApi.ts
  packages/zowe-explorer-api/src/vscode/ZoweVsCodeExtension.ts
  packages/zowe-explorer-api/src/vscode/doc/VscSettings.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/extending/ZoweExplorerZosmfApi.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/ZoweUSSNode.unit.test.ts
Labels: size/L

#3335 fix(v3): Migrate/recall updates in tree and filesystem
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/ZoweDatasetNode.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
  packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
Labels: size/L

#3333 fix(v2): Update migrated and recalled data sets in tree
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/dataset/ZoweDatasetNode.unit.test.ts
  packages/zowe-explorer/src/dataset/ZoweDatasetNode.ts
  packages/zowe-explorer/src/dataset/actions.ts
Labels: size/L
