Repository zowe/zowe-explorer-vscode, pull requests merged in 2024-09, with the labels that each got.

#3082 fix(v2): `onProfilesUpdate` does not always fire for extenders
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/src/shared/init.ts
Labels: size/S

#3083 fix(v3): `onProfilesUpdate` does not always fire for extenders
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/src/trees/shared/SharedInit.ts
Labels: size/S

#3084 Fix Unix Command behavior
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/commands/UnixCommandHandler.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/commands/UnixCommandHandler.ts
  packages/zowe-explorer/src/configuration/Profiles.ts
Labels: size/L

#3087 Update next with latest Zowe SDKs
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer/package.json
  pnpm-lock.yaml
Labels: no-changelog, size/L

#3090 ci: Automated merge-by comments and table
  .github/workflows/merge-by-comments.yml
  .github/workflows/merge-by-table.yml
  .github/workflows/merge-by/build-table-and-notify.js
  .github/workflows/merge-by/post-date.js
Labels: no-changelog, size/L

#3063 release: `v2.18.0`
  .github/release.config.js
  .github/workflows/deployment.yml
  lerna.json
  packages/eslint-plugin-zowe-explorer/CHANGELOG.md
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer/CHANGELOG.md
Labels: size/S

#3097 ci(v3): Automated merge-by comments and table
  .github/workflows/merge-by-comments.yml
  .github/workflows/merge-by-table.yml
  .github/workflows/merge-by/build-table-and-notify.js
  .github/workflows/merge-by/post-date.js
Labels: size/L

#3096 chore(v3): Update `release.config.js`
  .github/release.config.js
Labels: size/S

#3094 V3 pre-release Sept week 1
  lerna.json
  packages/eslint-plugin-zowe-explorer/CHANGELOG.md
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer/CHANGELOG.md
Labels: no-changelog, size/L

#3093 fix(list): Do not fetch directory URIs in `stat`
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/UssFSProvider.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
  packages/zowe-explorer/src/trees/uss/UssFSProvider.ts
Labels: size/L

#3101 [v3] add next back to release.config
  .github/release.config.js
  lerna.json
  packages/zowe-explorer/l10n/bundle.l10n.json
Labels: no-changelog, size/S

#3067 feat: Support member wildcards in favorited searches
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/src/tree/IZoweTreeNode.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
  packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
Labels: size/L

#3102 Fix: Add missing workflow permissions (main)
  .github/workflows/auto-comment.yml
  .github/workflows/update-project.yml
Labels: size/XS

#3109 Update function-bind dep for technical currency
  package.json
  samples/menu-item-sample/yarn.lock
  samples/tree-view-sample/yarn.lock
  samples/uss-profile-sample/yarn.lock
  samples/vue-webview-sample/yarn.lock
  yarn.lock
Labels: no-changelog, size/XXL

#3105 chore(v3): Fix ZE activation and commands failing when team config contains JSON error
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__mocks__/vscode.ts
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/extending/ZoweExplorerExtender.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
  packages/zowe-explorer/src/configuration/Profiles.ts
  packages/zowe-explorer/src/extending/ZoweExplorerExtender.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
Labels: size/L

#3098 Prompt to update credentials when outdated credentials stored securely in SSH profile
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/src/commands/UnixCommandHandler.ts
  packages/zowe-explorer/src/utils/AuthUtils.ts
Labels: size/S

#3106 v3 pre-release Sept week 2
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/profiles/ProfilesCache.unit.test.ts
  packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
  packages/zowe-explorer/CHANGELOG.md
Labels: no-changelog, size/S

#3107 [v2] Fix for extension failure with refresh Zowe Explorer command
  .github/workflows/auto-comment.yml
  .github/workflows/update-project.yml
  package.json
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/utils/LoggerUtils.unit.test.ts
  packages/zowe-explorer/src/globals.ts
  packages/zowe-explorer/src/utils/LoggerUtils.ts
  packages/zowe-explorer/src/utils/SettingsConfig.ts
  samples/menu-item-sample/yarn.lock
  samples/tree-view-sample/yarn.lock
  samples/uss-profile-sample/yarn.lock
  samples/vue-webview-sample/yarn.lock
  yarn.lock
Labels: size/XXL

#3115 fix(ux): Hide Zowe Resources panel until content is shown
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/vscode/ui/TableViewProvider.unit.test.ts
  packages/zowe-explorer-api/src/vscode/ui/TableViewProvider.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/package.json
Labels: size/M

#3116 fix(e2e/tests): Resolve flakiness for end-to-end tests
  packages/zowe-explorer/__tests__/__e2e__/README.md
  packages/zowe-explorer/__tests__/__e2e__/step_definitions/dialogs/IssueCommand.steps.ts
  packages/zowe-explorer/__tests__/__e2e__/step_definitions/edit/EditShared.steps.ts
  packages/zowe-explorer/__tests__/__e2e__/step_definitions/views/JobTableView.steps.ts
  packages/zowe-explorer/__tests__/__e2e__/wdio.conf.ts
  packages/zowe-explorer/package.json
  pnpm-lock.yaml
Labels: no-changelog, size/XL

#3076 Fix logout to give base profile precedence over parent profile
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/profiles/ProfilesCache.unit.test.ts
  packages/zowe-explorer-api/__tests__/__unit__/vscode/ZoweVsCodeExtension.unit.test.ts
  packages/zowe-explorer-api/__tests__/__unit__/vscode/ui/TableView.unit.test.ts
  packages/zowe-explorer-api/__tests__/__unit__/vscode/ui/utils/TableBuilder.unit.test.ts
  packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
  packages/zowe-explorer-api/src/vscode/ZoweVsCodeExtension.ts
  packages/zowe-explorer-api/src/vscode/doc/BaseProfileAuth.ts
  packages/zowe-explorer-api/src/vscode/doc/index.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/zosconsole/ZosConsolePanel.unit.test.ts
  packages/zowe-explorer/src/configuration/Profiles.ts
Labels: size/XL

#3132 fix(v3): Continue refresh even when team config doesn't exist
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/profiles/ProfilesCache.unit.test.ts
  packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
  packages/zowe-explorer/CHANGELOG.md
Labels: size/S

#3133 fix(v3): Not including extenders in Team config during creation
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/src/configuration/Profiles.ts
Labels: size/S

#3130 Update dev deps and fix code smells for V3
  package.json
  packages/zowe-explorer-api/__mocks__/mockUtils.ts
  packages/zowe-explorer/__tests__/__mocks__/mockUtils.ts
  packages/zowe-explorer/__tests__/__unit__/commands/ZoweCommandProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobActions.unit.test.ts
  packages/zowe-explorer/package.json
  packages/zowe-explorer/scripts/generatePoeditorJson.js
  packages/zowe-explorer/src/trees/uss/UssFSProvider.ts
  packages/zowe-explorer/src/webviews/package.json
  packages/zowe-explorer/src/webviews/src/certificate-wizard/App.tsx
  packages/zowe-explorer/src/webviews/src/edit-attributes/App.tsx
  packages/zowe-explorer/src/webviews/src/table-view/ContextMenu.tsx
  packages/zowe-explorer/src/webviews/src/zos-console/App.tsx
  packages/zowe-explorer/webpack.config.js
  pnpm-lock.yaml
  samples/vue-webview-sample/webviews/vue-sample/package.json
Labels: no-changelog, size/XXL

#3127 fix: add extensions back to Data Set resources; resolve USS copy/paste bug
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/fs/types/datasets.unit.test.ts
  packages/zowe-explorer-api/src/fs/types/datasets.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetUtils.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/UssFSProvider.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
  packages/zowe-explorer/src/trees/dataset/DatasetInit.ts
  packages/zowe-explorer/src/trees/dataset/DatasetUtils.ts
  packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
  packages/zowe-explorer/src/trees/uss/UssFSProvider.ts
  packages/zowe-explorer/src/trees/uss/ZoweUSSNode.ts
Labels: size/XL

#3135 Port Timothy's v2 PRs to v3 branch
  packages/zowe-explorer-api/__tests__/__unit__/profiles/ZoweExplorerZosmfApi.unit.test.ts
  packages/zowe-explorer-api/src/extend/MainframeInteraction.ts
  packages/zowe-explorer-api/src/profiles/ZoweExplorerZosmfApi.ts
  packages/zowe-explorer-api/src/utils/Poller.ts
  packages/zowe-explorer/__tests__/__mocks__/mockCreators/uss.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/ZoweDatasetNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/ZoweUSSNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/__snapshots__/ZoweUSSNode.unit.test.ts.snap
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/resources/dark/fileError.svg
  packages/zowe-explorer/resources/light/fileError.svg
  packages/zowe-explorer/src/commands/MvsCommandHandler.ts
  packages/zowe-explorer/src/configuration/Constants.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
  packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
  packages/zowe-explorer/src/trees/job/JobActions.ts
  packages/zowe-explorer/src/trees/job/ZoweJobNode.ts
  packages/zowe-explorer/src/trees/uss/USSTree.ts
  packages/zowe-explorer/src/trees/uss/ZoweUSSNode.ts
Labels: no-changelog, size/XL

#3144 To fix Strange behaviour of Job label under Job Favorites
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobTree.unit.test.ts
  packages/zowe-explorer/src/trees/job/ZoweJobNode.ts
Labels: size/M

#3145 Port #2768 V2 PR to V3(main)
  packages/zowe-explorer-api/src/tree/sorting.ts
  packages/zowe-explorer/__tests__/__mocks__/mockCreators/jobs.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobActions.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/trees/job/JobUtils.ts
  packages/zowe-explorer/src/trees/job/ZoweJobNode.ts
Labels: no-changelog, size/M

#3129 Update release config and add version to PNPM in README
  .github/release.config.js
  README.md
Labels: no-changelog, size/S

#3139 Update l10n script and add pnpm override
  package.json
  packages/zowe-explorer/scripts/generatePoeditorJson.js
  pnpm-lock.yaml
Labels: no-changelog, size/M

#3149 Add npm script to strip l10n comments
  .gitignore
  packages/zowe-explorer/package.json
  packages/zowe-explorer/scripts/stripL10nComments.js
Labels: no-changelog, size/S

#3140 Remove extRefresh cmd & FTP registration popup
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/src/extension.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedInit.unit.test.ts
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/package.nls.json
  packages/zowe-explorer/src/configuration/Constants.ts
  packages/zowe-explorer/src/extension.ts
  packages/zowe-explorer/src/trees/shared/SharedInit.ts
Labels: size/M

#3111 Fix credentials not refreshed in ds tree and misc profile related fixes
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/profiles/ProfilesCache.unit.test.ts
  packages/zowe-explorer-api/__tests__/__unit__/tree/ZoweTreeNode.unit.test.ts
  packages/zowe-explorer-api/__tests__/__unit__/vscode/ZoweVsCodeExtension.unit.test.ts
  packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
  packages/zowe-explorer-api/src/tree/ZoweTreeNode.ts
  packages/zowe-explorer-api/src/vscode/ZoweVsCodeExtension.ts
  packages/zowe-explorer-api/src/vscode/doc/PromptCredentials.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__integration__/bdd/features/profiles/UpdateCredentials.feature
  packages/zowe-explorer/__tests__/__integration__/bdd/step_definitions/profiles/UpdateCredentials.steps.ts
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetActions.extended.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedUtils.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSActions.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/configuration/Profiles.ts
  packages/zowe-explorer/src/icons/Icon.ts
  packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
  packages/zowe-explorer/src/trees/job/ZoweJobNode.ts
  packages/zowe-explorer/src/trees/uss/ZoweUSSNode.ts
  pnpm-lock.yaml
Labels: needs-ported, size/XL

#3136 Final v3 prerelease
  lerna.json
  packages/eslint-plugin-zowe-explorer/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
Labels: no-changelog, size/S

#3153 Fix deployment on next and push pre-release
  .github/workflows/deployment.yml
  lerna.json
Labels: no-changelog, size/XS

#3154 Update release.config.js to set channel for prerelease build
  .github/release.config.js
Labels: size/XS

#3155 Port 9/25 v3 prerelease
  .github/release.config.js
  lerna.json
  packages/eslint-plugin-zowe-explorer/CHANGELOG.md
  packages/eslint-plugin-zowe-explorer/package.json
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/src/webviews/package.json
  pnpm-lock.yaml
Labels: no-changelog, size/L

#3146 Update Zowe SDKs to v8 & FTP CLI plugin to v3
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/package.json
  pnpm-lock.yaml
  samples/uss-profile-sample/package.json
Labels: size/L

#3151 fix: resolve error when changing token to basic auth
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__mocks__/@zowe/imperative.ts
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/src/configuration/Profiles.ts
Labels: size/L
