Repository zowe/zowe-explorer-vscode, pull requests merged in 2024-12, with the labels that each got.

#3343 chore: remove samples from `v2-lts` branch
  .github/workflows/zowe-explorer-samples.yml
  packages/zowe-explorer/package.json
  packages/zowe-explorer/webpack.config.js
  samples/README.md
  samples/menu-item-sample/.eslintrc.js
  samples/menu-item-sample/.gitignore
  samples/menu-item-sample/.vscode/launch.json
  samples/menu-item-sample/.vscode/tasks.json
  samples/menu-item-sample/README.md
  samples/menu-item-sample/package.json
  samples/menu-item-sample/src/extension.ts
  samples/menu-item-sample/tsconfig.json
  samples/menu-item-sample/yarn.lock
  samples/tree-view-sample/.eslintrc.js
  samples/tree-view-sample/.gitignore
  samples/tree-view-sample/.vscode/launch.json
  samples/tree-view-sample/.vscode/tasks.json
  samples/tree-view-sample/README.md
  samples/tree-view-sample/package.json
  samples/tree-view-sample/src/ProfilesTreeProvider.ts
  samples/tree-view-sample/src/extension.ts
  samples/tree-view-sample/tsconfig.json
  samples/tree-view-sample/yarn.lock
  samples/uss-profile-sample/.eslintrc.js
  samples/uss-profile-sample/.gitignore
  samples/uss-profile-sample/.vscode/launch.json
  samples/uss-profile-sample/.vscode/tasks.json
  samples/uss-profile-sample/README.md
  samples/uss-profile-sample/package.json
  samples/uss-profile-sample/src/SshUssApi.ts
  samples/uss-profile-sample/src/extension.ts
  samples/uss-profile-sample/tsconfig.json
  samples/uss-profile-sample/yarn.lock
  samples/vue-webview-sample/.vscode/launch.json
  samples/vue-webview-sample/.vscode/tasks.json
  samples/vue-webview-sample/package.json
  samples/vue-webview-sample/src/extension.ts
  samples/vue-webview-sample/tsconfig.json
  samples/vue-webview-sample/webviews/vue-sample/index.html
  samples/vue-webview-sample/webviews/vue-sample/package.json
  samples/vue-webview-sample/webviews/vue-sample/src/App.vue
  samples/vue-webview-sample/webviews/vue-sample/src/components/HelloWorld.vue
  samples/vue-webview-sample/webviews/vue-sample/src/main.ts
  samples/vue-webview-sample/webviews/vue-sample/src/style.css
  samples/vue-webview-sample/webviews/vue-sample/src/vite-env.d.ts
  samples/vue-webview-sample/webviews/vue-sample/tsconfig.json
  samples/vue-webview-sample/webviews/vue-sample/tsconfig.node.json
  samples/vue-webview-sample/webviews/vue-sample/vite.config.ts
  samples/vue-webview-sample/webviews/vue-sample/yarn.lock
  samples/vue-webview-sample/yarn.lock
  yarn.lock
Labels: no-changelog, size/XXL

#3348 fix: TypeError when listing data sets after opening one w/ encoding
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/ZoweDatasetNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedUtils.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
Labels: size/M

#3341 ci: use shared action for merge-by updates
  .github/workflows/merge-by-comments.yml
  .github/workflows/merge-by-table.yml
  .github/workflows/merge-by/build-table-and-notify.js
  .github/workflows/merge-by/post-date.js
Labels: no-changelog, size/L

#3353 Add check for ISession before assigning proxy info
  packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
Labels: no-changelog, size/XS

#3356 fix(uss): Support "Pull from Mainframe" w/ binary files
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__mocks__/vscode.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSInit.unit.test.ts
  packages/zowe-explorer/src/trees/uss/USSInit.ts
Labels: size/S

#3362 [v2] fix(uss): Support "Pull from Mainframe" w/ binary files
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/src/uss/init.ts
Labels: size/XS

#3350 [v2] fix(uss): Opening file in tree causes focus to abruptly change
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/uss/ZoweUSSNode.unit.test.ts
  packages/zowe-explorer/src/uss/ZoweUSSNode.ts
  yarn.lock
Labels: size/M

#3359 fix(v2): Toggle off Auto Save and warn user after save error
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/abstract/ZoweSaveQueue.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/dataset/actions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/uss/actions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/workspace.unit.test.ts
  packages/zowe-explorer/i18n/sample/src/uss/USSTree.i18n.json
  packages/zowe-explorer/i18n/sample/src/utils/TreeViewUtils.i18n.json
  packages/zowe-explorer/i18n/sample/src/utils/workspace.i18n.json
  packages/zowe-explorer/src/abstract/ZoweSaveQueue.ts
  packages/zowe-explorer/src/dataset/actions.ts
  packages/zowe-explorer/src/uss/actions.ts
  packages/zowe-explorer/src/utils/workspace.ts
Labels: size/L

#3361 Add ability to view Job Spool with encoding
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/src/tree/IZoweTreeNode.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/ZoweJobNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedUtils.unit.test.ts
  packages/zowe-explorer/package.json
  packages/zowe-explorer/src/trees/job/JobFSProvider.ts
  packages/zowe-explorer/src/trees/job/JobTree.ts
  packages/zowe-explorer/src/trees/job/ZoweJobNode.ts
  packages/zowe-explorer/src/trees/shared/SharedUtils.ts
Labels: size/XXL

#3363 fix: store cached encoding by URI path instead of label/short path
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedUtils.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
  packages/zowe-explorer/src/trees/shared/SharedUtils.ts
  packages/zowe-explorer/src/trees/uss/ZoweUSSNode.ts
Labels: size/M
