Repository zowe/zowe-explorer-vscode, pull requests merged in 2024-01, with the labels that each got.

#2626 Handling-multiple-ssh-profiles - Unix Command Enhancements
  docs/early-access/v3/Extenders.md
  packages/zowe-explorer/__tests__/__unit__/command/unixCommandHandler.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/command/unixCommandHandlerTheia.unit.test.ts
  packages/zowe-explorer/i18n/sample/src/command/UnixCommandHandler.i18n.json
  packages/zowe-explorer/src/command/UnixCommandHandler.ts
Labels: no-changelog

#2649 2.13.1 Patch Release
  lerna.json
  package.json
  packages/eslint-plugin-zowe-explorer/CHANGELOG.md
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer/CHANGELOG.md
  samples/uss-profile-sample/package.json
  yarn.lock
Labels: no-changelog

#2653 Update main CHANGELOGS with 2.13.1 release
  README.md
  packages/eslint-plugin-zowe-explorer/CHANGELOG.md
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer/CHANGELOG.md
Labels: no-changelog

#2654 Add workflow to update issue and PR status on GH project board
  .github/workflows/update-project.yml
Labels: no-changelog

#2655 1.22.6 Release
  lerna.json
  packages/eslint-plugin-zowe-explorer/package.json
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer/package.json
Labels: no-changelog

#2636 fix(ProfileUtils.ts): remove redundant isTheia() function in favor of global variable
  packages/zowe-explorer/__tests__/__unit__/utils.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
Labels: no-changelog

#2648 Prepare v3 pre-release
  .github/workflows/theia-zowe-explorer-ci.yml
  docs/early-access/v3/Extenders.md
  lerna.json
  packages/eslint-plugin-zowe-explorer/CHANGELOG.md
  packages/eslint-plugin-zowe-explorer/package.json
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer/package.json
  pnpm-lock.yaml
Labels: v3, no-changelog

#2659 [v3] Make initForZowe argument profileTypeConfigurations required
  docs/early-access/v3/Extenders.md
  packages/eslint-plugin-zowe-explorer/CHANGELOG.md
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/src/extend/IApiExplorerExtender.ts
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/src/ZoweExplorerExtender.ts
Labels: API Extender, v3, Breaking Change

#2667 Add update-project.yml workflow to next branch
  .github/workflows/update-project.yml
Labels: no-changelog

#2668 Fix "Log out from API ML" missing from Manage Profile menu
  package.json
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
  packages/zowe-explorer-ftp-extension/__tests__/__unit__/Jes/ZoweExplorerFtpJesApi.unit.test.ts
  packages/zowe-explorer-ftp-extension/__tests__/__unit__/Mvs/ZoweExplorerFtpMvsApi.unit.test.ts
  packages/zowe-explorer-ftp-extension/__tests__/__unit__/Uss/ZoweExplorerFtpUssApi.unit.test.ts
  packages/zowe-explorer/src/Profiles.ts
  packages/zowe-explorer/src/utils/ProfileManagement.ts
  samples/uss-profile-sample/package.json
  samples/uss-profile-sample/yarn.lock
  yarn.lock
Labels: no-changelog

#2681 fix(uss): Fix error shown when deleting USS directory
  packages/zowe-explorer/src/uss/ZoweUSSNode.ts
Labels: no-changelog

#2661 Prepare 2.14.0 release
  lerna.json
  packages/eslint-plugin-zowe-explorer/CHANGELOG.md
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/README.md
  yarn.lock
Labels: no-changelog

#2686 build(api): Enhance watch task to trigger for zowe-explorer-api changes
  .gitignore
  package.json
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-api/tsconfig.json
  packages/zowe-explorer-ftp-extension/tsconfig.json
  packages/zowe-explorer-ftp-extension/webpack.config.js
  packages/zowe-explorer/package.json
  packages/zowe-explorer/tsconfig.json
  packages/zowe-explorer/webpack.config.js
Labels: no-changelog
