Repository zowe/zowe-explorer-vscode, pull requests merged in 2024-08, with the labels that each got.

#3036 Adjust imports to main
  packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpMvsApi.ts
  packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpUssApi.ts
  packages/zowe-explorer/src/shared/utils.ts
  packages/zowe-explorer/src/uss/actions.ts
Labels: no-changelog

#3038 Fix mustache import for webviews
  packages/zowe-explorer-api/src/vscode/ui/WebView.ts
Labels: no-changelog

#3021 types: Add missing return types, see #2952
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__mocks__/vscode.ts
  packages/zowe-explorer-api/src/extend/IApiExplorerExtender.ts
  packages/zowe-explorer-api/src/extend/MainframeInteraction.ts
  packages/zowe-explorer-api/src/fs/types/abstract.ts
  packages/zowe-explorer-api/src/tree/IZoweTree.ts
  packages/zowe-explorer-api/src/tree/IZoweTreeNode.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__mocks__/DatasetTree.ts
  packages/zowe-explorer/__tests__/__mocks__/USSTree.ts
  packages/zowe-explorer/__tests__/__unit__/commands/ZoweCommandProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/ZoweTreeProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/src/commands/ZoweCommandProvider.ts
  packages/zowe-explorer/src/configuration/Profiles.ts
  packages/zowe-explorer/src/trees/ZoweTreeProvider.ts
  packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
  packages/zowe-explorer/src/trees/job/JobTree.ts
  packages/zowe-explorer/src/trees/shared/SharedInit.ts
  packages/zowe-explorer/src/trees/uss/USSTree.ts
  packages/zowe-explorer/src/trees/uss/ZoweUSSNode.ts
  samples/uss-profile-sample/src/SshUssApi.ts
Labels: v3

#3044 Update CLI dependency in ZE API
  package.json
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer/package.json
  samples/uss-profile-sample/package.json
  yarn.lock
Labels: no-changelog

#3049 Update dependencies for technical currency
  package.json
  samples/vue-webview-sample/package.json
  samples/vue-webview-sample/webviews/vue-sample/package.json
  samples/vue-webview-sample/webviews/vue-sample/yarn.lock
  samples/vue-webview-sample/yarn.lock
  yarn.lock
Labels: no-changelog

#3019 feat(v3): Support logging in to multiple API ML instances
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/profiles/ProfilesCache.unit.test.ts
  packages/zowe-explorer-api/__tests__/__unit__/vscode/ZoweVsCodeExtension.unit.test.ts
  packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
  packages/zowe-explorer-api/src/vscode/ZoweVsCodeExtension.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__mocks__/mockCreators/shared.ts
  packages/zowe-explorer/__tests__/__unit__/commands/ZoweCommandProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/misc/ProfilesCache.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/misc/ZoweNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/ZoweDatasetNode.unit.test.ts
  packages/zowe-explorer/src/configuration/Profiles.ts
  packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
Labels: size/XL

#3050 feat: Jobs tabular view
  .eslintrc.yaml
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/vscode/ui/TableView.unit.test.ts
  packages/zowe-explorer-api/__tests__/__unit__/vscode/ui/TableViewProvider.unit.test.ts
  packages/zowe-explorer-api/src/Types.ts
  packages/zowe-explorer-api/src/vscode/ui/TableView.ts
  packages/zowe-explorer-api/src/vscode/ui/TableViewProvider.ts
  packages/zowe-explorer-api/src/vscode/ui/WebView.ts
  packages/zowe-explorer-api/src/vscode/ui/utils/HTMLTemplate.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__e2e__/features/views/JobTableView.feature
  packages/zowe-explorer/__tests__/__e2e__/step_definitions/views/JobTableView.steps.ts
  packages/zowe-explorer/__tests__/__e2e__/wdio.conf.ts
  packages/zowe-explorer/__tests__/__mocks__/mockCreators/jobs.ts
  packages/zowe-explorer/__tests__/__mocks__/mockUtils.ts
  packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobInit.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobTableView.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/package.nls.json
  packages/zowe-explorer/src/configuration/Constants.ts
  packages/zowe-explorer/src/trees/job/JobInit.ts
  packages/zowe-explorer/src/trees/job/JobTableView.ts
  packages/zowe-explorer/src/webviews/package.json
  packages/zowe-explorer/src/webviews/src/table-view/ActionsBar.tsx
  packages/zowe-explorer/src/webviews/src/table-view/ContextMenu.tsx
  packages/zowe-explorer/src/webviews/src/table-view/TableView.tsx
  packages/zowe-explorer/src/webviews/src/table-view/actionsColumn.tsx
  packages/zowe-explorer/src/webviews/src/table-view/style.css
  packages/zowe-explorer/src/webviews/src/table-view/types.ts
  packages/zowe-explorer/src/webviews/vite.config.ts
  pnpm-lock.yaml
Labels: size/XXL

#3040 refactor: FileSystemProvider remote lookup & change detection
  package.json
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/fs/BaseProvider.unit.test.ts
  packages/zowe-explorer-api/__tests__/__unit__/fs/utils/datasets.unit.test.ts
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-api/src/fs/BaseProvider.ts
  packages/zowe-explorer-api/src/fs/types/datasets.ts
  packages/zowe-explorer-api/src/fs/utils/FsAbstractUtils.ts
  packages/zowe-explorer-api/src/fs/utils/FsDatasetsUtils.ts
  packages/zowe-explorer-api/src/security/KeytarApi.ts
  packages/zowe-explorer-api/src/vscode/ZoweVsCodeExtension.ts
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__mocks__/vscode.ts
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/configuration/SettingsConfig.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTemplate.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/ZoweDatasetNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedInit.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedTreeProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/UssFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/ZoweUSSNode.unit.test.ts
  packages/zowe-explorer/package.json
  packages/zowe-explorer/src/configuration/Profiles.ts
  packages/zowe-explorer/src/configuration/SettingsConfig.ts
  packages/zowe-explorer/src/extending/ZoweExplorerExtender.ts
  packages/zowe-explorer/src/extension.ts
  packages/zowe-explorer/src/management/LocalFileManagement.ts
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTemplates.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
  packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
  packages/zowe-explorer/src/trees/job/JobFSProvider.ts
  packages/zowe-explorer/src/trees/shared/SharedInit.ts
  packages/zowe-explorer/src/trees/shared/SharedTreeProviders.ts
  packages/zowe-explorer/src/trees/uss/USSInit.ts
  packages/zowe-explorer/src/trees/uss/UssFSProvider.ts
  packages/zowe-explorer/src/trees/uss/ZoweUSSNode.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
  pnpm-lock.yaml
Labels: size/XXL

#3056 fix(console): Fix codicons in Theia and improve error handling
  packages/zowe-explorer-api/src/vscode/ui/WebView.ts
  packages/zowe-explorer-api/src/vscode/ui/utils/HTMLTemplate.ts
  packages/zowe-explorer/__tests__/__theia__/theia/extension.theiaChrome.ts
  packages/zowe-explorer/__tests__/__theia__/theia/extension.theiaFirefox.ts
  packages/zowe-explorer/__tests__/__unit__/zosconsole/ZosConsolePanel.unit.test.ts
  packages/zowe-explorer/package.json
  packages/zowe-explorer/src/webviews/src/zos-console/App.tsx
  packages/zowe-explorer/src/zosconsole/ZosConsolePanel.ts
  yarn.lock
Labels: no-changelog, size/L

#3060 deps: Use `es-toolkit` instead of `lodash` in webviews for tech. currency
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/src/webviews/package.json
  packages/zowe-explorer/src/webviews/src/edit-attributes/App.tsx
  packages/zowe-explorer/src/webviews/src/edit-history/components/PersistentTable/PersistentTableData.tsx
  pnpm-lock.yaml
Labels: size/S

#3051 fix(v3): Fix ZE V3 failing to load after upgrading from V1
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
  packages/zowe-explorer/src/configuration/Definitions.ts
  packages/zowe-explorer/src/configuration/SettingsConfig.ts
  packages/zowe-explorer/src/extension.ts
  packages/zowe-explorer/src/tools/ZoweLogger.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
Labels: size/L

#3064 Fix JSON errors are ignored when config files change on disk
  package.json
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/profiles/ProfilesCache.unit.test.ts
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/abstract/ZoweCommandProvider.unit.test.ts
  packages/zowe-explorer/src/Profiles.ts
  packages/zowe-explorer/src/shared/refresh.ts
  samples/uss-profile-sample/package.json
  yarn.lock
Labels: size/L

#3062 To port authentication switch support to next
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/management/ProfileManagement.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/configuration/Profiles.ts
  packages/zowe-explorer/src/management/ProfileManagement.ts
Labels: size/XL

#3075 Fix ZE activation and commands failing when team config contains JSON error
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__mocks__/vscode.ts
  packages/zowe-explorer/__tests__/__unit__/Profiles.extended.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/ZoweExplorerExtender.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
  packages/zowe-explorer/src/Profiles.ts
  packages/zowe-explorer/src/ZoweExplorerExtender.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
Labels: needs-ported, size/L

#3085 fix(v3): Hide conflict icons during normal diff; fix remote lookup causing local side of conflict to update
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/fs/BaseProvider.unit.test.ts
  packages/zowe-explorer-api/src/fs/BaseProvider.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/UssFSProvider.unit.test.ts
  packages/zowe-explorer/package.json
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
  packages/zowe-explorer/src/trees/uss/UssFSProvider.ts
Labels: size/M

#3057 3.0.0 Pre-release Aug 2024
  lerna.json
  packages/eslint-plugin-zowe-explorer/CHANGELOG.md
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/package.json
  packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
  pnpm-lock.yaml
Labels: size/XL
