Repository zowe/zowe-explorer-vscode, pull requests merged in 2024-10, with the labels that each got.

#3159 Prepare v3 GA Release
  docs/early-access/v3/Extenders.md
  lerna.json
  packages/eslint-plugin-zowe-explorer/CHANGELOG.md
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/package.json
  pnpm-lock.yaml
Labels: size/XL

#3164 Update release.config.js for Zowe V3 GA
  .github/release.config.js
Labels: size/S

#3138 fix(V3): Edit team config fails with global & project level present
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/src/configuration/Profiles.ts
Labels: size/S

#3163 fix: Add context to PS nodes (support opening within favorited search)
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
Labels: size/XS

#3170 [v2] fix(profiles): Pass `homeDir, projectDir` when creating `ProfileInfo` instance
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
Labels: size/S

#3177 Update Zowe SDKs to remove prerelease peer deps
  package.json
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-api/src/profiles/ZoweExplorerZosmfApi.ts
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer/package.json
  pnpm-lock.yaml
Labels: no-changelog, size/L

#3169 fix(profiles): Pass `homeDir, projectDir` when creating `ProfileInfo` instance
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
Labels: size/S

#3173 Remove sample VSCEs and restore carets for SDK deps
  .github/workflows/zowe-explorer-samples.yml
  .gitignore
  package.json
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-api/src/profiles/ZoweExplorerZosmfApi.ts
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer/package.json
  pnpm-lock.yaml
  samples/README.md
  samples/menu-item-sample/.eslintrc.js
  samples/menu-item-sample/.gitignore
  samples/menu-item-sample/.vscode/launch.json
  samples/menu-item-sample/.vscode/tasks.json
  samples/menu-item-sample/README.md
  samples/menu-item-sample/package.json
  samples/menu-item-sample/src/extension.ts
  samples/menu-item-sample/tsconfig.json
  samples/tree-view-sample/.eslintrc.js
  samples/tree-view-sample/.gitignore
  samples/tree-view-sample/.vscode/launch.json
  samples/tree-view-sample/.vscode/tasks.json
  samples/tree-view-sample/README.md
  samples/tree-view-sample/package.json
  samples/tree-view-sample/src/ProfilesTreeProvider.ts
  samples/tree-view-sample/src/extension.ts
  samples/tree-view-sample/tsconfig.json
  samples/uss-profile-sample/.eslintrc.js
  samples/uss-profile-sample/.gitignore
  samples/uss-profile-sample/.npmrc
  samples/uss-profile-sample/.vscode/launch.json
  samples/uss-profile-sample/.vscode/tasks.json
  samples/uss-profile-sample/README.md
  samples/uss-profile-sample/package.json
  samples/uss-profile-sample/src/SshUssApi.ts
  samples/uss-profile-sample/src/extension.ts
  samples/uss-profile-sample/tsconfig.json
  samples/vue-webview-sample/.vscode/launch.json
  samples/vue-webview-sample/.vscode/tasks.json
  samples/vue-webview-sample/package.json
  samples/vue-webview-sample/src/extension.ts
  samples/vue-webview-sample/tsconfig.json
  samples/vue-webview-sample/webviews/vue-sample/index.html
  samples/vue-webview-sample/webviews/vue-sample/package.json
  samples/vue-webview-sample/webviews/vue-sample/src/App.vue
  samples/vue-webview-sample/webviews/vue-sample/src/components/HelloWorld.vue
  samples/vue-webview-sample/webviews/vue-sample/src/main.ts
  samples/vue-webview-sample/webviews/vue-sample/src/style.css
  samples/vue-webview-sample/webviews/vue-sample/src/vite-env.d.ts
  samples/vue-webview-sample/webviews/vue-sample/tsconfig.json
  samples/vue-webview-sample/webviews/vue-sample/tsconfig.node.json
  samples/vue-webview-sample/webviews/vue-sample/vite.config.ts
Labels: no-changelog, size/XXL

#3189 fix: prompt optimizations for create file/dir; address case of skipping prompt
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSActions.unit.test.ts
  packages/zowe-explorer/src/trees/uss/USSActions.ts
Labels: size/L

#3192 fix(v2): prompt optimizations for create file/dir; address case of skipping prompt
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/uss/actions.unit.test.ts
  packages/zowe-explorer/src/uss/actions.ts
Labels: size/M

#3182 fix(ds): File extension detection misidentifies types
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetUtils.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/DatasetUtils.ts
Labels: size/S

#3157 Fix 401 error when opening PDS members after cred change
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/tree/ZoweTreeNode.unit.test.ts
  packages/zowe-explorer-api/src/fs/types/abstract.ts
  packages/zowe-explorer-api/src/tree/IZoweTreeNode.ts
  packages/zowe-explorer-api/src/tree/ZoweTreeNode.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__mocks__/@zowe/imperative.ts
  packages/zowe-explorer/__tests__/__mocks__/mockCreators/jobs.ts
  packages/zowe-explorer/__tests__/__unit__/trees/ZoweTreeProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/ZoweDatasetNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/ZoweJobNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedInit.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedUtils.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/ZoweUSSNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/configuration/Constants.ts
  packages/zowe-explorer/src/configuration/Profiles.ts
  packages/zowe-explorer/src/trees/ZoweTreeProvider.ts
  packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
  packages/zowe-explorer/src/trees/dataset/DatasetInit.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
  packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
  packages/zowe-explorer/src/trees/job/JobInit.ts
  packages/zowe-explorer/src/trees/job/JobTree.ts
  packages/zowe-explorer/src/trees/job/ZoweJobNode.ts
  packages/zowe-explorer/src/trees/shared/SharedInit.ts
  packages/zowe-explorer/src/trees/uss/USSInit.ts
  packages/zowe-explorer/src/trees/uss/USSTree.ts
  packages/zowe-explorer/src/trees/uss/ZoweUSSNode.ts
  packages/zowe-explorer/src/utils/AuthUtils.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
Labels: size/XXL

#3200 fix: resolve FTP getContents bug for MVS and USS
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/__mocks__/mockUtils.ts
  packages/zowe-explorer-ftp-extension/__tests__/__unit__/Mvs/ZoweExplorerFtpMvsApi.unit.test.ts
  packages/zowe-explorer-ftp-extension/__tests__/__unit__/Uss/ZoweExplorerFtpUssApi.unit.test.ts
  packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpMvsApi.ts
  packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpUssApi.ts
Labels: size/S

#3224 Fix children in tree nodes persisting on error
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/ZoweDatasetNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/ZoweJobNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/ZoweUSSNode.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
  packages/zowe-explorer/src/trees/job/ZoweJobNode.ts
  packages/zowe-explorer/src/trees/uss/ZoweUSSNode.ts
Labels: no-changelog, size/M

#3228 ci: change node versions on lint & deployment workflows
  .github/workflows/deployment.yml
  .github/workflows/lint.yml
Labels: size/XS

#3191 Improve process to build l10n bundle without comments
  packages/zowe-explorer/package.json
  packages/zowe-explorer/scripts/generatePoeditorJson.js
  packages/zowe-explorer/scripts/stripL10nComments.js
Labels: no-changelog, size/S

#3231 Port 3.0.1 missing release changes to main
  .github/dco.yml
  packages/eslint-plugin-zowe-explorer/CHANGELOG.md
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/__mocks__/mockUtils.ts
  packages/zowe-explorer/CHANGELOG.md
Labels: no-changelog, size/M

#3176 Prepare 1.22.9 release
  .github/workflows/deployment.yml
  .github/workflows/zowe-explorer-ci.yml
  lerna.json
  package.json
  packages/eslint-plugin-zowe-explorer/package.json
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/package.json
  yarn.lock
Labels: size/L

#3233 fix(ci): Use `ubuntu-22.04` images to get access to libsecret
  .github/workflows/zowe-explorer-ci.yml
Labels: no-changelog, size/S

#3237 chore: update workflows to trigger deployment of v1
  .github/workflows/deployment.yml
Labels: size/XS

#3240 [v1] Update secrets and permissions in deployment workflow
  .github/workflows/deployment.yml
Labels: size/XS

#3239 Removing icon names from translated strings
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/src/fs/BaseProvider.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/commands/MvsCommandHandler.ts
  packages/zowe-explorer/src/commands/TsoCommandHandler.ts
  packages/zowe-explorer/src/commands/UnixCommandHandler.ts
  packages/zowe-explorer/src/management/ProfileManagement.ts
  packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
  packages/zowe-explorer/src/trees/dataset/DatasetInit.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
  packages/zowe-explorer/src/trees/dataset/DatasetUtils.ts
  packages/zowe-explorer/src/trees/job/JobActions.ts
  packages/zowe-explorer/src/trees/job/JobFSProvider.ts
  packages/zowe-explorer/src/trees/job/JobInit.ts
  packages/zowe-explorer/src/trees/job/JobTree.ts
  packages/zowe-explorer/src/trees/job/JobUtils.ts
  packages/zowe-explorer/src/trees/uss/USSInit.ts
  packages/zowe-explorer/src/trees/uss/USSTree.ts
  packages/zowe-explorer/src/trees/uss/UssFSProvider.ts
Labels: size/L

#3241 [v2] Prepare deployment workflow for V2 patch releases
  .github/release.config.js
  .github/workflows/deployment.yml
Labels: size/S

#3248 fix(api): Fix profile references being lost when cache is refreshed
  packages/zowe-explorer-api/__tests__/__unit__/profiles/ProfilesCache.unit.test.ts
  packages/zowe-explorer-api/__tests__/__unit__/tree/ZoweTreeNode.unit.test.ts
  packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
  packages/zowe-explorer-api/src/tree/ZoweTreeNode.ts
  packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
  packages/zowe-explorer/src/trees/job/ZoweJobNode.ts
  packages/zowe-explorer/src/trees/uss/ZoweUSSNode.ts
  packages/zowe-explorer/src/utils/AuthUtils.ts
Labels: no-changelog, size/L

#3162 ZE Webview Localization
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/vscode/ui/TableView.unit.test.ts
  packages/zowe-explorer-api/src/vscode/ui/TableView.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedHistoryView.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSAttributeView.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/CertificateWizard.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/zosconsole/ZosConsolePanel.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/src/trees/shared/SharedHistoryView.ts
  packages/zowe-explorer/src/trees/uss/USSAttributeView.ts
  packages/zowe-explorer/src/utils/CertificateWizard.ts
  packages/zowe-explorer/src/webviews/src/certificate-wizard/App.tsx
  packages/zowe-explorer/src/webviews/src/edit-attributes/App.tsx
  packages/zowe-explorer/src/webviews/src/edit-history/App.tsx
  packages/zowe-explorer/src/webviews/src/edit-history/components/PersistentManagerHeader/PersistentManagerHeader.tsx
  packages/zowe-explorer/src/webviews/src/edit-history/components/PersistentTable/PersistentDataGridHeaders.tsx
  packages/zowe-explorer/src/webviews/src/edit-history/components/PersistentTable/PersistentDataPanel.tsx
  packages/zowe-explorer/src/webviews/src/edit-history/components/PersistentTable/PersistentTableData.tsx
  packages/zowe-explorer/src/webviews/src/edit-history/components/PersistentToolBar/PersistentAddNewHistoryItemButton.tsx
  packages/zowe-explorer/src/webviews/src/edit-history/components/PersistentToolBar/PersistentClearAllButton.tsx
  packages/zowe-explorer/src/webviews/src/edit-history/components/PersistentToolBar/PersistentDeleteSelectedButton.tsx
  packages/zowe-explorer/src/webviews/src/edit-history/components/PersistentToolBar/PersistentDropdownOptions.tsx
  packages/zowe-explorer/src/webviews/src/edit-history/components/PersistentToolBar/PersistentRefreshButton.tsx
  packages/zowe-explorer/src/webviews/src/edit-history/components/PersistentUtils.ts
  packages/zowe-explorer/src/webviews/src/table-view/ActionsBar.tsx
  packages/zowe-explorer/src/webviews/src/table-view/TableView.tsx
  packages/zowe-explorer/src/webviews/src/zos-console/App.tsx
  packages/zowe-explorer/src/zosconsole/ZosConsolePanel.ts
Labels: size/XL

#3246 fix: Move v1 conversion prompt into initialization
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/configuration/Definitions.ts
  packages/zowe-explorer/src/extension.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
Labels: size/L

#3249 refactor(jobs): Update contents of editor during polling / "Pull from Mainframe"
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobFSProvider.unit.test.ts
  packages/zowe-explorer/src/trees/job/JobFSProvider.ts
Labels: size/S

#3174 feat: Detect JWT expiration in token values and prompt user if expired
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__mocks__/mockCreators/shared.ts
  packages/zowe-explorer/__tests__/__unit__/trees/ZoweTreeProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSTree.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/src/trees/ZoweTreeProvider.ts
  packages/zowe-explorer/src/utils/AuthUtils.ts
  pnpm-lock.yaml
Labels: size/L

#3253 fix(uss): Fix encoding of USS file not automatically detected
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedUtils.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/UssFSProvider.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/trees/shared/SharedUtils.ts
  packages/zowe-explorer/src/trees/uss/UssFSProvider.ts
Labels: needs-ported, size/L

#3256 fix: add ProfileInfo.getTeamConfig.exists check to v1 profile prompt
  packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
Labels: no-changelog, size/M

#3257 polish changelogs
  packages/eslint-plugin-zowe-explorer/CHANGELOG.md
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer/CHANGELOG.md
Labels: no-changelog, size/XS

#3258 trigger deployment with dummy change to lerna
  lerna.json
Labels: no-changelog, size/XS

#3262 chore: update changelogs for main w/ v3.0.2 content
  packages/eslint-plugin-zowe-explorer/CHANGELOG.md
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer/CHANGELOG.md
Labels: size/S

#3263 Remove duplicate build:nlsExtract from package.json for webview localization
  packages/zowe-explorer/package.json
  packages/zowe-explorer/src/webviews/src/edit-history/components/PersistentUtils.ts
  packages/zowe-explorer/src/webviews/src/table-view/ActionsBar.tsx
Labels: no-changelog, size/S

#3255 DatasetFSprovider fetchDataset() - fix behavior with non-existent datasets and members
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
Labels: size/L

#3245 ci: only notify users for merge-by during scheduled run
  .github/workflows/merge-by/build-table-and-notify.js
Labels: no-changelog, size/S

#3261 fix: use `vscode.workspace.fs` for `delete` and `rename`
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__mocks__/vscode.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/ZoweUSSNode.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
  packages/zowe-explorer/src/trees/job/JobFSProvider.ts
  packages/zowe-explorer/src/trees/job/JobTree.ts
  packages/zowe-explorer/src/trees/uss/USSTree.ts
  packages/zowe-explorer/src/trees/uss/ZoweUSSNode.ts
Labels: size/M

#3259 Allow deployment workflow to be triggered manually
  .github/workflows/deployment.yml
Labels: size/S

#3275 Fix: To resolve error message upon switching the authentication methods
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/configuration/Profiles.ts
Labels: size/L

#3274 fix: "Show Config" button in error dialog does not work during initialization
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__integration__/bdd/features/dialogs/ShowConfigErrorDialog.feature
  packages/zowe-explorer/__tests__/__integration__/bdd/step_definitions/dialogs/ShowConfigErrorDialog.steps.ts
  packages/zowe-explorer/__tests__/__integration__/bdd/step_definitions/profiles/UpdateCredentials.steps.ts
  packages/zowe-explorer/__tests__/__integration__/bdd/wdio.conf.ts
  packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
  packages/zowe-explorer/src/configuration/Profiles.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
Labels: size/L

#3268 fix(ds): Call remoteLookupForResource when entry doesn't exist locally
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
Labels: size/S

#3282 feat: 'Add to Workspace' context menu option (Data Sets & USS resources)
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__mocks__/vscode.ts
  packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedInit.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedUtils.unit.test.ts
  packages/zowe-explorer/package.json
  packages/zowe-explorer/package.nls.json
  packages/zowe-explorer/src/configuration/Constants.ts
  packages/zowe-explorer/src/trees/shared/SharedInit.ts
  packages/zowe-explorer/src/trees/shared/SharedUtils.ts
Labels: size/L

#3271 feat: open Zowe Explorer resources using VSCode URLs
  packages/zowe-explorer-api/__mocks__/vscode.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__mocks__/vscode.ts
  packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedUtils.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/UriHandler.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/package.nls.json
  packages/zowe-explorer/src/configuration/Constants.ts
  packages/zowe-explorer/src/trees/shared/SharedInit.ts
  packages/zowe-explorer/src/trees/shared/SharedUtils.ts
  packages/zowe-explorer/src/utils/UriHandler.ts
Labels: size/L

#3279 DatasetFSProvider.readFile() makes at most one API call
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
Labels: bug, size/L

#3287 Updates to webpack and package.json scripts for minimization
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer-ftp-extension/webpack.config.js
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/webpack.config.js
Labels: Technical Debt, no-changelog, size/M

#3281 fix: Only show "No configs detected" prompt if ZE opened
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetInit.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
  packages/zowe-explorer/src/extension.ts
  packages/zowe-explorer/src/trees/dataset/DatasetInit.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
Labels: bug, size/M
