Repository zowe/zowe-explorer-vscode, pull requests merged in 2025-02, with the labels that each got.

#3421 Port 3.1.0 release changes to main
  .github/release.config.js
  lerna.json
  packages/eslint-plugin-zowe-explorer/CHANGELOG.md
  packages/eslint-plugin-zowe-explorer/package.json
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/README.md
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/README.md
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/package.json
  packages/zowe-explorer/src/webviews/package.json
  pnpm-lock.yaml
Labels: no-changelog, size/M

#3428 fix(error): Check if `session` is valid before calling proxy setup fn
  packages/zowe-explorer-api/__tests__/__unit__/profiles/ZoweExplorerZosmfApi.unit.test.ts
  packages/zowe-explorer-api/src/profiles/ZoweExplorerZosmfApi.ts
  packages/zowe-explorer/CHANGELOG.md
Labels: no-changelog, size/M

#3433 Update dev deps to resolve Dependabot alerts
  packages/zowe-explorer/src/webviews/package.json
  pnpm-lock.yaml
Labels: no-changelog, size/M

#3413 Support for drag/drop of MVS files across LPAR'S
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
  packages/zowe-explorer/src/trees/shared/SharedUtils.ts
  packages/zowe-explorer/src/trees/uss/USSTree.ts
Labels: size/L

#3435 Port #3428 into `release/3.1` (prep for 3.1.1 release)
  packages/zowe-explorer-api/__tests__/__unit__/profiles/ZoweExplorerZosmfApi.unit.test.ts
  packages/zowe-explorer-api/src/profiles/ZoweExplorerZosmfApi.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
Labels: size/M

#3437 Port #3417 Delete Keybinding fix
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSInit.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/trees/uss/USSActions.ts
  packages/zowe-explorer/src/trees/uss/USSInit.ts
Labels: size/M

#3439 Unable to open a Renamed Sequential DS
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
Labels: size/XS

#3438 Add ErrorHandling for OpenWithEncoding function
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobTree.unit.test.ts
  packages/zowe-explorer/src/trees/job/JobTree.ts
Labels: no-changelog, size/S

#3440 Fix cancelling MVS/TSO command causing error
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/commands/MvsCommandHandler.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/commands/TsoCommandHandler.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/commands/UnixCommandHandler.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/commands/ZoweCommandProvider.unit.test.ts
  packages/zowe-explorer/src/commands/ZoweCommandProvider.ts
Labels: size/M

#3441 Fix edit history does not show the correct information
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/src/trees/shared/SharedHistoryView.ts
  packages/zowe-explorer/src/webviews/src/edit-history/App.tsx
  packages/zowe-explorer/src/webviews/src/edit-history/components/PersistentTable/PersistentDataPanel.tsx
Labels: size/M

#3436 Prepare 3.1.1 release
  lerna.json
Labels: no-changelog, size/XS

#3456 refactor(TableViewProvider): make constructor & properties protected
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/src/vscode/ui/TableViewProvider.ts
Labels: size/S

#3460 Port 3.1.1 to main, CHANGELOGS
  packages/eslint-plugin-zowe-explorer/CHANGELOG.md
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSActions.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/trees/uss/USSActions.ts
Labels: no-changelog, size/M

#3464 Port #3441 into release/3.1
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/src/trees/shared/SharedHistoryView.ts
  packages/zowe-explorer/src/webviews/src/edit-history/App.tsx
  packages/zowe-explorer/src/webviews/src/edit-history/components/PersistentTable/PersistentDataPanel.tsx
Labels: size/M

#3461 Port #3438 into release/3.1
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobTree.unit.test.ts
  packages/zowe-explorer/src/trees/job/JobTree.ts
Labels: no-changelog, size/S

#3465 Port #3440 to release/3.1
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/commands/MvsCommandHandler.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/commands/TsoCommandHandler.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/commands/UnixCommandHandler.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/commands/ZoweCommandProvider.unit.test.ts
  packages/zowe-explorer/src/commands/ZoweCommandProvider.ts
Labels: size/S

#3467 fix: update-sdks to fix cross-lpar copy alc unit
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer/package.json
  pnpm-lock.yaml
Labels: no-changelog, size/S

#3459 ZE API for direct connect login/logout & adoption in ZE processes
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/vscode/ZoweVsCodeExtension.unit.test.ts
  packages/zowe-explorer-api/src/profiles/AuthHandler.ts
  packages/zowe-explorer-api/src/vscode/ZoweVsCodeExtension.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/configuration/Profiles.ts
Labels: size/L

#3457 fix to use profile encoding rather than metadata encoding during upload and download of dataset and uss files
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/UssFSProvider.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
  packages/zowe-explorer/src/trees/uss/UssFSProvider.ts
Labels: size/M

#3453 Unable to open a Sequential DS after renaming a favourited Sequential DS
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
Labels: no-changelog, size/L

#3445 Various improvements to z/OS console panel
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/package.json
  packages/zowe-explorer/package.nls.json
  packages/zowe-explorer/src/webviews/src/zos-console/App.tsx
  packages/zowe-explorer/src/webviews/src/zos-console/index.html
Labels: size/M

#3481 fix: Use `initialSort` instead of `sort` in table column definitions
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetActions.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
  packages/zowe-explorer/src/trees/job/JobTableView.ts
  packages/zowe-explorer/src/webviews/src/table-view/types.ts
Labels: size/S

#3479 refactor(node/ds): Make recall/migration logic more reliable
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/ZoweDatasetNode.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
  packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
Labels: size/L
