Repository zowe/zowe-explorer-vscode, pull requests merged in 2025-09, with the labels that each got.

#3837 Update release notes with 3.3 features
  packages/zowe-explorer/release-notes.md
  packages/zowe-explorer/resources/release-notes/3.1-jobs-table-2.png
  packages/zowe-explorer/resources/release-notes/3.1-jobs-table-2.webp
  packages/zowe-explorer/resources/release-notes/3.1-search-1.png
  packages/zowe-explorer/resources/release-notes/3.1-search-1.webp
  packages/zowe-explorer/resources/release-notes/3.2-ds-pagination-1.png
  packages/zowe-explorer/resources/release-notes/3.2-ds-pagination-1.webp
  packages/zowe-explorer/resources/release-notes/3.3-active-jobs-polling-1.webp
  packages/zowe-explorer/resources/release-notes/3.3-active-jobs-polling-2.png
  packages/zowe-explorer/resources/release-notes/3.3-ds-table-1.webp
Labels: no-changelog, size/M

#3849 Update dev dependencies for technical currency
  packages/zowe-explorer/src/webviews/package.json
  pnpm-lock.yaml
Labels: no-changelog, size/XS

#3835 Prepare v3.3.0 Release
  lerna.json
  packages/zowe-explorer-api/__tests__/__unit__/vscode/ZoweVsCodeExtension.unit.test.ts
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/README.md
  packages/zowe-explorer-ftp-extension/docs/README.md
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer/README.md
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/release-notes.md
  packages/zowe-explorer/resources/release-notes/3.1-jobs-table-2.png
  packages/zowe-explorer/resources/release-notes/3.1-jobs-table-2.webp
  packages/zowe-explorer/resources/release-notes/3.1-search-1.png
  packages/zowe-explorer/resources/release-notes/3.1-search-1.webp
  packages/zowe-explorer/resources/release-notes/3.2-ds-pagination-1.png
  packages/zowe-explorer/resources/release-notes/3.2-ds-pagination-1.webp
  packages/zowe-explorer/resources/release-notes/3.3-active-jobs-polling-1.webp
  packages/zowe-explorer/resources/release-notes/3.3-active-jobs-polling-2.png
  packages/zowe-explorer/resources/release-notes/3.3-ds-table-1.webp
  packages/zowe-explorer/src/configuration/Profiles.ts
Labels: size/L

#3851 Bump version to 3.4.0-SNAPSHOT
  lerna.json
  packages/eslint-plugin-zowe-explorer/CHANGELOG.md
  packages/eslint-plugin-zowe-explorer/package.json
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/package.json
  packages/zowe-explorer/src/webviews/package.json
  pnpm-lock.yaml
Labels: size/M

#3845 Delete VSAM datasets from Zowe Explorer View
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/profiles/ZoweExplorerZosmfApi.unit.test.ts
  packages/zowe-explorer-api/src/profiles/ZoweExplorerZosmfApi.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
  packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
Labels: size/L

#3834 dev: Update pnpm from v8 to v10
  .github/workflows/audit.yml
  .github/workflows/changelog.yml
  .github/workflows/circular-deps.yml
  .github/workflows/deployment.yml
  .github/workflows/lint.yml
  .github/workflows/report-artifact-pr.yml
  .github/workflows/zowe-explorer-ci.yml
  .github/workflows/zowe-explorer-ftp-ci.yml
  .npmrc
  README.md
  package.json
  packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
  packages/zowe-explorer-api/src/security/KeytarCredentialManager.ts
  packages/zowe-explorer/src/webviews/src/table-view/ActionsBar.tsx
  pnpm-lock.yaml
Labels: no-changelog, size/M

#3872 Update dev deps for technical currency
  package.json
  packages/zowe-explorer/package.json
  pnpm-lock.yaml
Labels: no-changelog, size/S

#3878 Update `tar-fs` transitive dependency for audit
  pnpm-lock.yaml
Labels: size/XS

#3879 Update `tar-fs` transitive dependency for audit [v2]
  package.json
  yarn.lock
Labels: size/S
