Repository zowe/zowe-explorer-vscode, pull requests merged in 2025-03, with the labels that each got.

#3482 Fix for extenders favorites not loading after registration
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/src/tree/IZoweTree.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/extending/ZoweExplorerExtender.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/ZoweTreeProvider.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/extending/ZoweExplorerExtender.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
  packages/zowe-explorer/src/trees/job/JobTree.ts
  packages/zowe-explorer/src/trees/uss/USSTree.ts
Labels: size/M

#3462 Fix UNIX attributes refresh button
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/src/tree/IZoweTreeNode.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSAttributeView.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/ZoweUSSNode.unit.test.ts
  packages/zowe-explorer/src/trees/uss/USSAttributeView.ts
  packages/zowe-explorer/src/trees/uss/ZoweUSSNode.ts
Labels: size/L

#3480 Debounce credential prompts and check profile locks in more places
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/profiles/AuthHandler.unit.test.ts
  packages/zowe-explorer-api/src/profiles/AuthHandler.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/UssFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/ZoweUSSNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/AuthUtils.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
  packages/zowe-explorer/src/trees/shared/SharedInit.ts
  packages/zowe-explorer/src/trees/uss/UssFSProvider.ts
  packages/zowe-explorer/src/utils/AuthUtils.ts
Labels: size/XL

#3369 Add new settings for default dataset & job sort orders
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/ZoweTreeProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedUtils.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/package.nls.json
  packages/zowe-explorer/src/configuration/Constants.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
  packages/zowe-explorer/src/trees/dataset/DatasetUtils.ts
  packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
  packages/zowe-explorer/src/trees/job/JobTree.ts
  packages/zowe-explorer/src/trees/job/JobUtils.ts
  packages/zowe-explorer/src/trees/job/ZoweJobNode.ts
  packages/zowe-explorer/src/trees/shared/SharedUtils.ts
Labels: size/XL

#3484 rewriting/editing ReadMe file
  packages/zowe-explorer/README.md
Labels: docs, no-changelog, size/L

#3503 fix(ftp): Only return 401 error if authentication fails
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/__mocks__/@zowe/zowe-explorer-api.ts
  packages/zowe-explorer-ftp-extension/__tests__/__unit__/FtpApi/ZoweExplorerAbstractFtpApi.unit.test.ts
  packages/zowe-explorer-ftp-extension/__tests__/__unit__/extension.unit.test.ts
  packages/zowe-explorer-ftp-extension/src/ZoweExplorerAbstractFtpApi.ts
  packages/zowe-explorer-ftp-extension/src/extension.ts
Labels: no-changelog, size/M

#3507 fix(jobs): Respect profile encoding when opening spool files
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobFSProvider.unit.test.ts
  packages/zowe-explorer/src/trees/job/JobFSProvider.ts
  packages/zowe-explorer/src/trees/shared/SharedUtils.ts
Labels: size/M

#3515 ports: recent bug fixes for 3.1.2 release
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/profiles/AuthHandler.unit.test.ts
  packages/zowe-explorer-api/src/profiles/AuthHandler.ts
  packages/zowe-explorer-api/src/vscode/ui/TableViewProvider.ts
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/__mocks__/@zowe/zowe-explorer-api.ts
  packages/zowe-explorer-ftp-extension/__tests__/__unit__/FtpApi/ZoweExplorerAbstractFtpApi.unit.test.ts
  packages/zowe-explorer-ftp-extension/__tests__/__unit__/extension.unit.test.ts
  packages/zowe-explorer-ftp-extension/src/ZoweExplorerAbstractFtpApi.ts
  packages/zowe-explorer-ftp-extension/src/extension.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/ZoweDatasetNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/UssFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/ZoweUSSNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/AuthUtils.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
  packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
  packages/zowe-explorer/src/trees/job/JobTableView.ts
  packages/zowe-explorer/src/trees/shared/SharedInit.ts
  packages/zowe-explorer/src/trees/uss/UssFSProvider.ts
  packages/zowe-explorer/src/utils/AuthUtils.ts
  packages/zowe-explorer/src/webviews/src/table-view/types.ts
Labels: size/XXL

#3521 Added "Copy Name" option to VSAM data sets
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/README.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetActions.unit.test.ts
  packages/zowe-explorer/package.json
  packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
Labels: size/M

#3522 fix: avoid extra prompts when replacing conflicting member on creation
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/Profiles.extended.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/dataset/actions.unit.test.ts
  packages/zowe-explorer/src/dataset/actions.ts
Labels: size/M

#3525 fix: Only check if token has expired when profile's API supports it
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/ZoweTreeProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/ZoweJobNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/AuthUtils.unit.test.ts
  packages/zowe-explorer/src/configuration/Constants.ts
  packages/zowe-explorer/src/trees/ZoweTreeProvider.ts
  packages/zowe-explorer/src/utils/AuthUtils.ts
Labels: size/L

#3477 Bug fixes on open recent member command
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedActions.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/package.nls.json
  packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
  packages/zowe-explorer/src/trees/shared/SharedActions.ts
Labels: size/L

#3527 To provide client side certificate support for zosmf
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/src/profiles/ZoweExplorerZosmfApi.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/src/configuration/Profiles.ts
Labels: size/M

#3531 port: line overwritten by another port; avoid using cached profiles
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/UssFSProvider.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
  packages/zowe-explorer/src/trees/uss/UssFSProvider.ts
Labels: no-changelog, size/M

#3536 Prepare 2.18.1 release
  lerna.json
  packages/eslint-plugin-zowe-explorer/CHANGELOG.md
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer/CHANGELOG.md
Labels: no-changelog, size/S

#3535 Prepare 3.1.2 release
  lerna.json
  packages/eslint-plugin-zowe-explorer/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
Labels: no-changelog, size/L

#3550 Cherry-picked the commits related to the release
  packages/eslint-plugin-zowe-explorer/CHANGELOG.md
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
Labels: size/L

#3539 Fix wrong context menu options after deleting members
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetActions.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
  packages/zowe-explorer/src/utils/TreeViewUtils.ts
Labels: size/S

#3551 fix(v2): Show Attributes not working for VSAM data sets
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/dataset/init.unit.test.ts
  packages/zowe-explorer/src/dataset/init.ts
Labels: size/XS

#3552 v2: Fix wrong context menu options after deleting members
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/dataset/actions.unit.test.ts
  packages/zowe-explorer/src/dataset/actions.ts
  packages/zowe-explorer/src/utils/TreeViewUtils.ts
Labels: size/S

#3524 refactor: Improve `autoStore` handling, resolve refresh race conditions
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/src/tree/IZoweTree.ts
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/__tests__/__unit__/FtpApi/ZoweExplorerAbstractFtpApi.unit.test.ts
  packages/zowe-explorer-ftp-extension/__tests__/__unit__/Jes/ZoweExplorerFtpJesApi.unit.test.ts
  packages/zowe-explorer-ftp-extension/__tests__/__unit__/Mvs/ZoweExplorerFtpMvsApi.unit.test.ts
  packages/zowe-explorer-ftp-extension/__tests__/__unit__/Uss/ZoweExplorerFtpUssApi.unit.test.ts
  packages/zowe-explorer-ftp-extension/src/ZoweExplorerAbstractFtpApi.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__mocks__/mockCreators/datasets.ts
  packages/zowe-explorer/__tests__/__mocks__/mockCreators/shared.ts
  packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/ZoweTreeProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetInit.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/ZoweDatasetNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobInit.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/ZoweJobNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedInit.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedUtils.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSInit.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/ZoweUSSNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/AuthUtils.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/TreeViewUtils.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/src/configuration/Constants.ts
  packages/zowe-explorer/src/trees/ZoweTreeProvider.ts
  packages/zowe-explorer/src/trees/dataset/DatasetInit.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
  packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
  packages/zowe-explorer/src/trees/job/JobInit.ts
  packages/zowe-explorer/src/trees/job/JobTree.ts
  packages/zowe-explorer/src/trees/job/ZoweJobNode.ts
  packages/zowe-explorer/src/trees/shared/SharedActions.ts
  packages/zowe-explorer/src/trees/shared/SharedInit.ts
  packages/zowe-explorer/src/trees/shared/SharedUtils.ts
  packages/zowe-explorer/src/trees/uss/USSActions.ts
  packages/zowe-explorer/src/trees/uss/USSInit.ts
  packages/zowe-explorer/src/trees/uss/USSTree.ts
  packages/zowe-explorer/src/trees/uss/ZoweUSSNode.ts
  packages/zowe-explorer/src/utils/AuthUtils.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
  packages/zowe-explorer/src/utils/TreeViewUtils.ts
Labels: size/XXL
