Repository zowe/zowe-explorer-vscode, pull requests merged in 2025-06, with the labels that each got.

#3675 Prepare 3.2.1 release
  lerna.json
  packages/eslint-plugin-zowe-explorer/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/src/configuration/Profiles.ts
Labels: no-changelog, size/S

#3683 Port 3.2.1 release to main
  packages/eslint-plugin-zowe-explorer/CHANGELOG.md
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer/CHANGELOG.md
Labels: no-changelog, size/M

#3663 feat: Add `zedc status`, `zedc test coverage` commands
  zedc/CHANGELOG.md
  zedc/Cargo.lock
  zedc/Cargo.toml
  zedc/src/cmd.rs
  zedc/src/code/mod.rs
  zedc/src/code/prepare.rs
  zedc/src/main.rs
  zedc/src/pm/cmd.rs
  zedc/src/pm/mod.rs
  zedc/src/status.rs
  zedc/src/test/cmd.rs
  zedc/src/test/coverage.rs
  zedc/src/test/fs.rs
  zedc/src/test/local/mod.rs
  zedc/src/test/mod.rs
  zedc/src/util.rs
Labels: size/XXL

#3685 chore(v2): set resolution for `tar-fs` to resolve vuln in dev dep (`vsce`)
  package.json
  yarn.lock
Labels: no-changelog, size/S

#3686 chore: resolve tar-fs@2 vuln in lockfile
  package.json
  pnpm-lock.yaml
Labels: size/XS

#3680 Add the ability to open a data set from selected text in the editor
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetInit.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetUtils.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/package.nls.json
  packages/zowe-explorer/src/configuration/Constants.ts
  packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
  packages/zowe-explorer/src/trees/dataset/DatasetInit.ts
  packages/zowe-explorer/src/trees/dataset/DatasetUtils.ts
Labels: size/XL

#3694 fix(v2): Allow profile node to be refreshed using its refresh action button
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/src/uss/init.ts
Labels: size/XS

#3692 Update merge-by-table.yml to continue on error
  .github/workflows/merge-by-table.yml
Labels: size/XS

#3697 zedc(fix): code coverage path mismatch, look for `ZOWE_OPT_PASSWORD`
  zedc/CHANGELOG.md
  zedc/Cargo.lock
  zedc/Cargo.toml
  zedc/src/status.rs
  zedc/src/test/coverage.rs
Labels: size/L

#3704 ci(v2): Fix GH project status for pull requests
  .github/workflows/update-project.yml
  yarn.lock
Labels: no-changelog, size/S

#3703 ci(v3): Fix GH project status for pull requests
  .github/workflows/update-project.yml
  pnpm-lock.yaml
Labels: no-changelog, size/XS

#3657 Add release notes page on startup
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/vscode/ui/WebView.unit.test.ts
  packages/zowe-explorer-api/src/vscode/ui/WebView.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__e2e__/wdio.conf.ts
  packages/zowe-explorer/__tests__/__integration__/bdd/features/ReleaseNotes.feature
  packages/zowe-explorer/__tests__/__integration__/bdd/step_definitions/ReleaseNotes.steps.ts
  packages/zowe-explorer/__tests__/__integration__/bdd/wdio.conf.ts
  packages/zowe-explorer/__tests__/__mocks__/vscode.ts
  packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedInit.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/ReleaseNotes.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/package.nls.json
  packages/zowe-explorer/release-notes.md
  packages/zowe-explorer/resources/release-notes/3.1-jobs-table-1.png
  packages/zowe-explorer/resources/release-notes/3.1-jobs-table-2.png
  packages/zowe-explorer/resources/release-notes/3.1-search-1.png
  packages/zowe-explorer/resources/release-notes/3.1-workspace-1.png
  packages/zowe-explorer/resources/release-notes/3.1-workspace-2.png
  packages/zowe-explorer/resources/release-notes/3.2-default-sort-1.png
  packages/zowe-explorer/resources/release-notes/3.2-default-sort-2.png
  packages/zowe-explorer/resources/release-notes/3.2-default-sort-3.png
  packages/zowe-explorer/resources/release-notes/3.2-ds-pagination-1.png
  packages/zowe-explorer/resources/release-notes/3.2-hover-1.png
  packages/zowe-explorer/resources/release-notes/3.2-job-spool-1.png
  packages/zowe-explorer/resources/release-notes/3.2-search-1.png
  packages/zowe-explorer/resources/release-notes/3.2-search-2.png
  packages/zowe-explorer/resources/release-notes/3.2-uss-filter-1.png
  packages/zowe-explorer/resources/release-notes/3.2-uss-filter-2.png
  packages/zowe-explorer/src/configuration/Constants.ts
  packages/zowe-explorer/src/configuration/Definitions.ts
  packages/zowe-explorer/src/tools/ZoweLocalStorage.ts
  packages/zowe-explorer/src/trees/shared/SharedHistoryView.ts
  packages/zowe-explorer/src/trees/shared/SharedInit.ts
  packages/zowe-explorer/src/utils/ReleaseNotes.ts
  packages/zowe-explorer/src/webviews/package.json
  packages/zowe-explorer/src/webviews/src/release-notes/App.tsx
  packages/zowe-explorer/src/webviews/src/release-notes/index.html
  packages/zowe-explorer/src/webviews/src/release-notes/index.tsx
  packages/zowe-explorer/src/webviews/src/release-notes/resources/background-img.svg
  packages/zowe-explorer/src/webviews/src/release-notes/style.css
  packages/zowe-explorer/src/webviews/vite.config.ts
  pnpm-lock.yaml
Labels: size/XXL

#3678 fix: Extender load on refresh
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/src/fs/utils/FsAbstractUtils.ts
  packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__mocks__/@zowe/imperative.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/UssFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/extending/ZoweExplorerExtender.ts
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
  packages/zowe-explorer/src/trees/uss/UssFSProvider.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
Labels: size/XXL
