Repository zowe/zowe-explorer-vscode, pull requests merged in 2025-08, with the labels that each got.

#3779 refactor(ds/table): Add Pin/Unpin to context menu
  packages/zowe-explorer-api/src/vscode/ui/TableView.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTableView.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTableView.ts
  packages/zowe-explorer/src/webviews/src/table-view/ActionUtils.ts
  packages/zowe-explorer/src/webviews/src/table-view/ActionsBar.tsx
  packages/zowe-explorer/src/webviews/src/table-view/ContextMenu.tsx
  packages/zowe-explorer/src/webviews/src/table-view/ContextMenuItem.tsx
Labels: no-changelog, size/XL

#3775 fix(regression): Handle uncaught exception in `ZoweTreeNode.getProfile`
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/tree/ZoweTreeNode.unit.test.ts
  packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
  packages/zowe-explorer-api/src/tree/ZoweTreeNode.ts
  packages/zowe-explorer/CHANGELOG.md
Labels: size/M

#3794 fix(ds/table): UX adjustments, fix Back button not hiding
  packages/zowe-explorer-api/__tests__/__unit__/vscode/ui/TableView.unit.test.ts
  packages/zowe-explorer-api/src/vscode/ui/TableView.ts
  packages/zowe-explorer/__tests__/__e2e__/step_definitions/views/DatasetTableView.steps.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTableView.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/trees/dataset/DatasetTableView.ts
  packages/zowe-explorer/src/webviews/src/table-view/ActionButton.tsx
  packages/zowe-explorer/src/webviews/src/table-view/ActionUtils.ts
  packages/zowe-explorer/src/webviews/src/table-view/ContextMenu.tsx
  packages/zowe-explorer/src/webviews/src/table-view/TableView.tsx
Labels: no-changelog, size/L

#3806 fix: allow editing existing DS/USS filters
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSTree.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
  packages/zowe-explorer/src/trees/uss/USSTree.ts
Labels: no-changelog, size/L

#3791 Fix: Prevent Data Loss - Handle Long Records in Save Process
  .eslintrc.yaml
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/src/utils/ErrorCorrelator.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__mocks__/vscode.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
  packages/zowe-explorer/src/trees/dataset/DatasetUtils.ts
  packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
Labels: size/XL

#3764 feat(jobs): Poll active jobs & notify on job completion
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/src/Types.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobInit.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobTree.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/package.nls.json
  packages/zowe-explorer/src/configuration/Constants.ts
  packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
  packages/zowe-explorer/src/trees/job/JobInit.ts
  packages/zowe-explorer/src/trees/job/JobTree.ts
Labels: size/XL

#3809 fix: null-like access in `AuthUtils.handleProfileAuthOnError`
  package.json
  packages/zowe-explorer/src/utils/AuthUtils.ts
  pnpm-lock.yaml
Labels: no-changelog, size/XS

#3810 fix: Use a Just-In-Time approach for LRECL validation
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
  packages/zowe-explorer/src/trees/dataset/DatasetUtils.ts
Labels: no-changelog, size/L

#3814 Add certificate check to Profiles.checkCurrentProfile for profile status checks
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/profiles/ProfilesCache.unit.test.ts
  packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/configuration/Profiles.ts
Labels: bug, size/L

#3731 Fixing binary dataset transfer via drag and drop across LPARs
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
Labels: size/L

#3818 fix(ds): Do not allow listing data sets while filter prompt is open
  packages/zowe-explorer-api/src/tree/IZoweTreeNode.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/ZoweDatasetNode.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
  packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
  packages/zowe-explorer/src/utils/AuthUtils.ts
Labels: no-changelog, size/XL
