Repository zowe/zowe-explorer-vscode, pull requests merged in 2025-01, with the labels that each got.

#3373 Update workflows and deps for technical currency
  .github/workflows/codeql.yml
  .github/workflows/zowe-explorer-ci.yml
  packages/zowe-explorer/__tests__/__unit__/commands/ZoweCommandProvider.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/DatasetInit.ts
  packages/zowe-explorer/src/utils/AuthUtils.ts
  pnpm-lock.yaml
Labels: no-changelog, size/M

#3375 Remove the Delete Profile menu option
  docs/images/ZE-v2-delete-profile.gif
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/README.md
  packages/zowe-explorer/__tests__/__unit__/management/ProfileManagement.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/src/configuration/Profiles.ts
  packages/zowe-explorer/src/management/ProfileManagement.ts
Labels: size/L

#3374 [v2] Update workflows and deps for technical currency
  .github/workflows/codeql.yml
  .github/workflows/zowe-explorer-ci.yml
  yarn.lock
Labels: size/L

#3377 [v2] Port fix for Open with Encoding quickpick
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/shared/utils.unit.test.ts
  packages/zowe-explorer/src/shared/utils.ts
Labels: size/S

#3365 ZE and ZE API readme updates
  packages/zowe-explorer-api/README.md
  packages/zowe-explorer/README.md
Labels: no-changelog, size/S

#3370 refactor: Lock profiles during async operations (phase 1: filesystem)
  .eslintrc.yaml
  .prettierignore
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__mocks__/vscode.ts
  packages/zowe-explorer-api/__tests__/__unit__/profiles/AuthHandler.unit.test.ts
  packages/zowe-explorer-api/__tests__/__unit__/utils/DeferredPromise.unit.test.ts
  packages/zowe-explorer-api/__tests__/__unit__/utils/FileManagement.unit.test.ts
  packages/zowe-explorer-api/__tests__/__unit__/utils/files.unit.test.ts
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-api/src/profiles/AuthHandler.ts
  packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
  packages/zowe-explorer-api/src/profiles/index.ts
  packages/zowe-explorer-api/src/utils/DeferredPromise.ts
  packages/zowe-explorer-api/src/utils/FileManagement.ts
  packages/zowe-explorer-api/src/utils/index.ts
  packages/zowe-explorer-api/src/vscode/ZoweVsCodeExtension.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__common__/testUtils.ts
  packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedInit.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/UssFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/AuthUtils.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
  packages/zowe-explorer/src/configuration/Profiles.ts
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
  packages/zowe-explorer/src/trees/job/JobFSProvider.ts
  packages/zowe-explorer/src/trees/shared/SharedInit.ts
  packages/zowe-explorer/src/trees/uss/UssFSProvider.ts
  packages/zowe-explorer/src/utils/AuthUtils.ts
  packages/zowe-explorer/src/utils/CertificateWizard.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
  pnpm-lock.yaml
Labels: size/XL

#3349 [v2] Port fix for credentials not refreshed in ds tree and other misc profile fixes
  packages/zowe-explorer-api/__tests__/__unit__/tree/ZoweTreeNode.unit.test.ts
  packages/zowe-explorer-api/__tests__/__unit__/vscode/ZoweVsCodeExtension.unit.test.ts
  packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
  packages/zowe-explorer-api/src/tree/ZoweTreeNode.ts
  packages/zowe-explorer-api/src/vscode/ZoweVsCodeExtension.ts
  packages/zowe-explorer-api/src/vscode/doc/IPromptCredentials.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__mocks__/vscode.ts
  packages/zowe-explorer/__tests__/__unit__/Profiles.extended.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/dataset/actions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/mvs/mvsNodeActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/shared/actions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/uss/actions.unit.test.ts
  packages/zowe-explorer/i18n/sample/src/Profiles.i18n.json
  packages/zowe-explorer/src/Profiles.ts
  packages/zowe-explorer/src/generators/icons/items/home.ts
Labels: size/XL

#3376 [v2] Port fixes for invalid credential handling
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__theia__/theia/extension.theiaChrome.ts
  packages/zowe-explorer/__tests__/__unit__/Profiles.extended.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/ZoweNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/abstract/ZoweTreeProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/dataset/ZoweDatasetNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/job/ZoweJobNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/shared/init.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/shared/utils.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/uss/ZoweUSSNode.unit.test.ts
  packages/zowe-explorer/i18n/sample/src/dataset/DatasetTree.i18n.json
  packages/zowe-explorer/i18n/sample/src/dataset/ZoweDatasetNode.i18n.json
  packages/zowe-explorer/i18n/sample/src/job/ZoweJobNode.i18n.json
  packages/zowe-explorer/i18n/sample/src/uss/ZoweUSSNode.i18n.json
  packages/zowe-explorer/src/Profiles.ts
  packages/zowe-explorer/src/abstract/ZoweTreeProvider.ts
  packages/zowe-explorer/src/dataset/DatasetTree.ts
  packages/zowe-explorer/src/dataset/ZoweDatasetNode.ts
  packages/zowe-explorer/src/globals.ts
  packages/zowe-explorer/src/job/ZosJobsProvider.ts
  packages/zowe-explorer/src/job/ZoweJobNode.ts
  packages/zowe-explorer/src/shared/IZoweTreeOpts.ts
  packages/zowe-explorer/src/shared/TreeProviders.ts
  packages/zowe-explorer/src/shared/context.ts
  packages/zowe-explorer/src/shared/init.ts
  packages/zowe-explorer/src/shared/refresh.ts
  packages/zowe-explorer/src/uss/USSTree.ts
  packages/zowe-explorer/src/uss/ZoweUSSNode.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
Labels: size/XXL

#3383 Update to latest Zowe SDKs
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/package.json
  pnpm-lock.yaml
Labels: size/L

#3079 feat: Introduce integrated terminal
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/profiles/ZoweExplorerZosmfApi.unit.test.ts
  packages/zowe-explorer-api/src/extend/MainframeInteraction.ts
  packages/zowe-explorer-api/src/profiles/UserSettings.ts
  packages/zowe-explorer-api/src/profiles/ZoweExplorerZosmfApi.ts
  packages/zowe-explorer-api/src/tree/ZoweTreeNode.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__mocks__/@zowe/imperative.ts
  packages/zowe-explorer/__tests__/__unit__/commands/MvsCommandHandler.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/commands/TsoCommandHandler.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/commands/UnixCommandHandler.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/commands/ZoweCommandProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/configuration/SettingsConfig.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/tools/ZoweTerminal.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/tools/__snapshots__/ZoweTerminal.unit.test.ts.snap
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedHistoryView.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedInit.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/package.nls.json
  packages/zowe-explorer/src/commands/MvsCommandHandler.ts
  packages/zowe-explorer/src/commands/TsoCommandHandler.ts
  packages/zowe-explorer/src/commands/UnixCommandHandler.ts
  packages/zowe-explorer/src/commands/ZoweCommandProvider.ts
  packages/zowe-explorer/src/configuration/Constants.ts
  packages/zowe-explorer/src/configuration/Definitions.ts
  packages/zowe-explorer/src/configuration/Profiles.ts
  packages/zowe-explorer/src/configuration/SettingsConfig.ts
  packages/zowe-explorer/src/tools/ZoweLocalStorage.ts
  packages/zowe-explorer/src/tools/ZoweTerminal.ts
  packages/zowe-explorer/src/trees/shared/SharedHistoryView.ts
  packages/zowe-explorer/src/trees/shared/SharedInit.ts
  packages/zowe-explorer/src/trees/uss/USSActions.ts
  packages/zowe-explorer/src/webviews/src/edit-history/App.tsx
  packages/zowe-explorer/src/webviews/src/edit-history/components/PersistentTable/PersistentDataPanel.tsx
  packages/zowe-explorer/src/webviews/src/edit-history/types.ts
Labels: size/XXL

#3392 fix: Avoid data-loss when creating new members
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetActions.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
Labels: needs-ported, size/M

#3389 feat: Add time started, submitted and ended fields to Jobs table view
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__mocks__/mockCreators/jobs.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobTableView.unit.test.ts
  packages/zowe-explorer/src/trees/job/JobTableView.ts
  packages/zowe-explorer/src/webviews/src/table-view/style.css
Labels: size/M

#3397 fix: Avoid data-loss when creating new members (#3392)
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetActions.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
Labels: size/M

#3406 chore: downgrade ubuntu runners to ubuntu-22.04
  .github/workflows/audit.yml
  .github/workflows/auto-comment.yml
  .github/workflows/changelog.yml
  .github/workflows/circular-deps.yml
  .github/workflows/codeql.yml
  .github/workflows/deployment.yml
  .github/workflows/lint.yml
  .github/workflows/merge-by-comments.yml
  .github/workflows/merge-by-table.yml
  .github/workflows/stale.yml
  .github/workflows/update-project.yml
  .github/workflows/zowe-explorer-ci.yml
  .github/workflows/zowe-explorer-ftp-ci.yml
Labels: no-changelog, size/M

#3409 fix: call Mutex.waitForUnlock instead of locking profile before request
  packages/zowe-explorer-api/__tests__/__unit__/profiles/AuthHandler.unit.test.ts
  packages/zowe-explorer-api/src/profiles/AuthHandler.ts
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
  packages/zowe-explorer/src/trees/job/JobFSProvider.ts
  packages/zowe-explorer/src/trees/uss/UssFSProvider.ts
Labels: no-changelog, size/L

#3407 fix(ds): Pass correct DS name in `stat` when doing remote lookup
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
Labels: size/M

#3412 Fix internal error when extenders register new profile types
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSTree.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
  packages/zowe-explorer/src/trees/job/JobTree.ts
  packages/zowe-explorer/src/trees/uss/USSTree.ts
Labels: size/L

#3387 Support for copy/paste of MVS files within and cross lpars
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/profiles/ZoweExplorerZosmfApi.unit.test.ts
  packages/zowe-explorer-api/src/extend/MainframeInteraction.ts
  packages/zowe-explorer-api/src/profiles/ZoweExplorerZosmfApi.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetInit.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
  packages/zowe-explorer/src/trees/dataset/DatasetInit.ts
  packages/zowe-explorer/src/trees/dataset/DatasetUtils.ts
Labels: size/XXL

#3416 Fix internal error when extenders register new profile types (#3412)
  .github/workflows/audit.yml
  .github/workflows/auto-comment.yml
  .github/workflows/changelog.yml
  .github/workflows/circular-deps.yml
  .github/workflows/codeql.yml
  .github/workflows/deployment.yml
  .github/workflows/lint.yml
  .github/workflows/merge-by-comments.yml
  .github/workflows/merge-by-table.yml
  .github/workflows/stale.yml
  .github/workflows/update-project.yml
  .github/workflows/zowe-explorer-ci.yml
  .github/workflows/zowe-explorer-ftp-ci.yml
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSTree.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
  packages/zowe-explorer/src/trees/job/JobTree.ts
  packages/zowe-explorer/src/trees/uss/USSTree.ts
Labels: size/L

#3398 Prepare 3.1.0 release
  lerna.json
  packages/eslint-plugin-zowe-explorer/CHANGELOG.md
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/profiles/AuthHandler.unit.test.ts
  packages/zowe-explorer-api/src/profiles/AuthHandler.ts
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/README.md
  packages/zowe-explorer/README.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
  packages/zowe-explorer/src/trees/job/JobFSProvider.ts
  packages/zowe-explorer/src/trees/uss/UssFSProvider.ts
Labels: no-changelog, size/L

#3393 fix(v2): avoid data-loss when creating new members
  packages/zowe-explorer-ftp-extension/__tests__/__unit__/Jes/ZoweExplorerFtpJesApi.unit.test.ts
  packages/zowe-explorer-ftp-extension/__tests__/__unit__/Mvs/ZoweExplorerFtpMvsApi.unit.test.ts
  packages/zowe-explorer-ftp-extension/__tests__/__unit__/Uss/ZoweExplorerFtpUssApi.unit.test.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/dataset/actions.unit.test.ts
  packages/zowe-explorer/src/dataset/actions.ts
Labels: size/L

#3417 fix: Pass TreeView selection when node is undefined
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSInit.unit.test.ts
  packages/zowe-explorer/src/trees/uss/USSActions.ts
  packages/zowe-explorer/src/trees/uss/USSInit.ts
Labels: size/M
