Repository zowe/zowe-explorer-vscode, pull requests merged in 2025-05, with the labels that each got.

#3630 fix(ds): return empty list to paginator when request fails
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/ZoweDatasetNode.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
Labels: no-changelog, size/M

#3616 Job Spool Pagination Bug fixes
  packages/zowe-explorer-api/__tests__/__unit__/vscode/ui/PaginationCodeLens.unit.test.ts
  packages/zowe-explorer-api/src/vscode/ui/PaginationCodeLens.ts
  packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobInit.unit.test.ts
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/package.nls.json
  packages/zowe-explorer/src/configuration/Constants.ts
  packages/zowe-explorer/src/extending/ZoweExplorerExtender.ts
  packages/zowe-explorer/src/trees/job/JobActions.ts
  packages/zowe-explorer/src/trees/job/JobFSProvider.ts
  packages/zowe-explorer/src/trees/job/JobInit.ts
Labels: no-changelog, size/L

#3631 Add the newly added requestCompletionTimeout to Zowe Explorer
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/profiles/ZoweExplorerZosmfApi.unit.test.ts
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-api/src/profiles/ZoweExplorerZosmfApi.ts
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/package.nls.json
  pnpm-lock.yaml
Labels: size/L

#3626 Dragging and Dropping Datasets with members bug fix
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
Labels: size/L

#3615 Fix: Userid desync in ZE profiles tooltip
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/ZoweDatasetNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
  packages/zowe-explorer/src/configuration/Profiles.ts
  packages/zowe-explorer/src/trees/ZoweTreeProvider.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
  packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
  packages/zowe-explorer/src/utils/AuthUtils.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
Labels: no-changelog, size/L

#3648 Fix missing message insert for overwriting config file
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/src/vscode/ZoweVsCodeExtension.ts
Labels: size/S

#3629 revised Readme
  packages/zowe-explorer/README.md
Labels: docs, size/L

#3665 Add PR checklist item to test new functionality with FTP extender type
  .github/PULL_REQUEST_TEMPLATE.md
Labels: no-changelog, size/XS

#3538 fix for iterminal quirks
  packages/zowe-explorer-api/__tests__/__unit__/tree/pagination.unit.test.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/tools/ZoweTerminal.unit.test.ts
  packages/zowe-explorer/src/tools/ZoweTerminal.ts
Labels: no-changelog, size/M

#3650 Fix report artifact workflow failing on fork PR
  .github/workflows/merge-by-comments.yml
  .github/workflows/report-artifact-pr.yml
Labels: no-changelog, size/XS

#3655 Fix: Switch Auth Method misbehaviour
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/src/configuration/Profiles.ts
Labels: size/L

#3668 Update SDKs (resolves log4js issue) and resolve Dependabot alerts
  package.json
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/package.json
  packages/zowe-explorer/src/webviews/package.json
  pnpm-lock.yaml
Labels: size/M

#3671 Port Fixes #3655 #3668
  package.json
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/src/configuration/Profiles.ts
  packages/zowe-explorer/src/webviews/package.json
  pnpm-lock.yaml
Labels: size/L
