Repository zowe/zowe-explorer-vscode, pull requests merged in 2025-04, with the labels that each got.

#3520 Feature: creation of team config moved to ZE API and adopted by ZE
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__mocks__/mockCreators/shared.ts
  packages/zowe-explorer-api/__tests__/__unit__/profiles/ProfilesCache.unit.test.ts
  packages/zowe-explorer-api/__tests__/__unit__/vscode/ZoweVsCodeExtension-ext.unit.test.ts
  packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
  packages/zowe-explorer-api/src/vscode/ZoweVsCodeExtension.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/src/configuration/Profiles.ts
Labels: size/XL

#3546 fix: Prevent data-lost on move operation :yum:
  packages/zowe-explorer-api/__tests__/__unit__/profiles/AuthHandler.unit.test.ts
  packages/zowe-explorer-api/__tests__/__unit__/utils/FileManagement.unit.test.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
Labels: no-changelog, size/L

#3559 Update dev deps for technical currency
  package.json
  packages/zowe-explorer/src/webviews/package.json
  pnpm-lock.yaml
Labels: no-changelog, size/S

#3526 Add data set search case sensitivity (#3455)
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__mocks__/vscode.ts
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-api/src/globals/Gui.ts
  packages/zowe-explorer-api/src/tree/IZoweTree.ts
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__mocks__/mockCreators/datasets.ts
  packages/zowe-explorer/__tests__/__mocks__/vscode.ts
  packages/zowe-explorer/__tests__/__unit__/tools/ZowePersistentFilters.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetInit.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetSearch.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedHistoryView.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/src/configuration/Constants.ts
  packages/zowe-explorer/src/configuration/Definitions.ts
  packages/zowe-explorer/src/tools/ZoweLocalStorage.ts
  packages/zowe-explorer/src/tools/ZowePersistentFilters.ts
  packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
  packages/zowe-explorer/src/trees/dataset/DatasetInit.ts
  packages/zowe-explorer/src/trees/dataset/DatasetSearch.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTemplates.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
  packages/zowe-explorer/src/trees/shared/SharedHistoryView.ts
  packages/zowe-explorer/src/webviews/src/edit-history/components/PersistentTable/PersistentDataGridHeaders.tsx
  packages/zowe-explorer/src/webviews/src/edit-history/components/PersistentTable/PersistentTableData.tsx
  packages/zowe-explorer/src/webviews/src/edit-history/components/PersistentToolBar/PersistentClearAllButton.tsx
  packages/zowe-explorer/src/webviews/src/edit-history/components/PersistentToolBar/PersistentDeleteSelectedButton.tsx
  packages/zowe-explorer/src/webviews/src/edit-history/components/PersistentToolBar/PersistentDropdownOptions.tsx
  pnpm-lock.yaml
Labels: size/XXL

#3560 fix: optional chaining inconsistencies spotted by security tool
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
Labels: no-changelog, size/S

#3558 Fix: Same-lpar copy/paste of empty PDS results in an error
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetActions.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
Labels: size/M

#3562 Update open recent shortcut
  packages/zowe-explorer/README.md
Labels: no-changelog, size/XS

#3569 Rebuild lockfile to update dev deps
  pnpm-lock.yaml
Labels: no-changelog, size/XS

#3572 Make it clear in README that user must install PNPM 8.x
  README.md
Labels: size/XS

#3566 Remove note about secure credential storage from bug template
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: no-changelog, size/XS

#3576 V3: chore: update SDKs to address numeric encoding issue
  package.json
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedUtils.unit.test.ts
  packages/zowe-explorer/package.json
  packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
  packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
  packages/zowe-explorer/src/trees/shared/SharedUtils.ts
  packages/zowe-explorer/src/webviews/package.json
  pnpm-lock.yaml
Labels: size/M

#3578 fix: request attributes when using `mvsApi.dataSet` (older API)
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/ZoweDatasetNode.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
Labels: size/S

#3577 V2: chore: update SDKs to address numeric encoding issue
  package.json
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer-ftp-extension/src/ftpSession.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/shared/utils.unit.test.ts
  packages/zowe-explorer/i18n/sample/src/shared/utils.i18n.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/src/shared/utils.ts
  yarn.lock
Labels: size/L

#3589 Fix stale bot ignoring most issues
  .github/workflows/stale.yml
Labels: no-changelog, size/XS

#3592 chore: update stale config options
  .github/workflows/stale.yml
Labels: no-changelog, size/XS

#3588 Update @wdio/cucumber-framework to support Node 22
  .github/workflows/zowe-explorer-ci.yml
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer/__tests__/__common__/base.wdio.conf.ts
  packages/zowe-explorer/__tests__/__e2e__/wdio.conf.ts
  packages/zowe-explorer/__tests__/__integration__/bdd/wdio.conf.ts
  packages/zowe-explorer/package.json
  pnpm-lock.yaml
Labels: no-changelog, size/M

#3584 fix(ds): Respect extensions when creating new member & detecting remote changes
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/src/vscode/ui/WebView.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetActions.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
Labels: size/M

#3519 feat(uss): Add filterBy and cd .. commands
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSTree.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/package.nls.json
  packages/zowe-explorer/src/configuration/Constants.ts
  packages/zowe-explorer/src/trees/uss/USSInit.ts
  packages/zowe-explorer/src/trees/uss/USSTree.ts
Labels: size/L

#3590 Fix duplicate favorite nodes for extenders
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSTree.unit.test.ts
  packages/zowe-explorer/package.json
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
  packages/zowe-explorer/src/trees/job/JobInit.ts
  packages/zowe-explorer/src/trees/job/JobTree.ts
  packages/zowe-explorer/src/trees/uss/USSTree.ts
  packages/zowe-explorer/src/webviews/package.json
Labels: size/L

#3591 ZE: Support Environment Variables
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/profiles/ProfilesCache.unit.test.ts
  packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/package.nls.json
  packages/zowe-explorer/src/configuration/Constants.ts
  packages/zowe-explorer/src/configuration/Profiles.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
Labels: size/L

#3596 Update ZE API README
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/README.md
Labels: size/M

#3568 Added Job spool pagination functionality
  README.md
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/vscode/ui/PaginationCodeLens.unit.test.ts
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-api/src/extend/MainframeInteraction.ts
  packages/zowe-explorer-api/src/profiles/ZoweExplorerZosmfApi.ts
  packages/zowe-explorer-api/src/vscode/ui/PaginationCodeLens.ts
  packages/zowe-explorer-api/src/vscode/ui/index.ts
  packages/zowe-explorer-ftp-extension/__tests__/__unit__/FtpApi/ZoweExplorerAbstractFtpApi.unit.test.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__mocks__/vscode.ts
  packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobInit.unit.test.ts
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/package.nls.json
  packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
  packages/zowe-explorer/src/trees/job/JobActions.ts
  packages/zowe-explorer/src/trees/job/JobFSProvider.ts
  packages/zowe-explorer/src/trees/job/JobInit.ts
Labels: size/L

#3575 User password plaintext fix
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/src/profiles/AuthHandler.ts
  packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__mocks__/mockCreators/shared.ts
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/ZoweTreeProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/ZoweJobNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/AuthUtils.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
  packages/zowe-explorer/src/configuration/Profiles.ts
  packages/zowe-explorer/src/trees/ZoweTreeProvider.ts
  packages/zowe-explorer/src/utils/AuthUtils.ts
Labels: size/L

#3585 feat: Pagination for listing data sets and PDS members
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/tree/pagination.unit.test.ts
  packages/zowe-explorer-api/src/globals/Constants.ts
  packages/zowe-explorer-api/src/tree/IZoweTreeNode.ts
  packages/zowe-explorer-api/src/tree/index.ts
  packages/zowe-explorer-api/src/tree/pagination.ts
  packages/zowe-explorer-api/src/vscode/ui/PaginationCodeLens.ts
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/__tests__/__unit__/Mvs/ZoweExplorerFtpMvsApi.unit.test.ts
  packages/zowe-explorer-ftp-extension/src/ZoweExplorerFtpMvsApi.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/ZoweDatasetNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobFSProvider.unit.test.ts
  packages/zowe-explorer/l10n/bundle.l10n.json
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/package.nls.json
  packages/zowe-explorer/src/configuration/Constants.ts
  packages/zowe-explorer/src/configuration/Definitions.ts
  packages/zowe-explorer/src/configuration/SettingsConfig.ts
  packages/zowe-explorer/src/trees/dataset/DatasetActions.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
  packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
  packages/zowe-explorer/src/trees/job/JobFSProvider.ts
  packages/zowe-explorer/src/trees/shared/SharedInit.ts
Labels: size/XXL

#3607 Replace import from source to import from module
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/src/extending/ZoweExplorerExtender.ts
Labels: bug, size/XS

#3603 fix: allow listing root in USS, fix edge case w/ `cd ..`
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSTree.unit.test.ts
  packages/zowe-explorer/src/trees/uss/USSTree.ts
Labels: needs-ported, size/S

#3614 fix: add optional chaining to tab input check
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/fs/BaseProvider.unit.test.ts
  packages/zowe-explorer-api/src/fs/BaseProvider.ts
  packages/zowe-explorer/CHANGELOG.md
Labels: size/S

#3609 fix: tree pagination edge cases (max items 0, descending pattern combos)
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/ZoweDatasetNode.unit.test.ts
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/package.nls.json
  packages/zowe-explorer/src/configuration/Constants.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
  packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
Labels: no-changelog, size/L

#3605 fix(v2): Allow listing root directory under USS profile
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/uss/USSTree.unit.test.ts
  packages/zowe-explorer/src/uss/USSTree.ts
Labels: size/M

#3611 Implement fixes for timeout validation and additional error details
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/profiles/ZoweExplorerZosmfApi.unit.test.ts
  packages/zowe-explorer-api/__tests__/__unit__/utils/ErrorCorrelator.unit.test.ts
  packages/zowe-explorer-api/__tests__/__unit__/vscode/doc/VscSettings.unit.test.ts
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-api/src/profiles/ZoweExplorerZosmfApi.ts
  packages/zowe-explorer-api/src/utils/ErrorCorrelator.ts
  packages/zowe-explorer-api/src/vscode/doc/VscSettings.ts
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/ZoweUSSNode.unit.test.ts
  packages/zowe-explorer/package.json
  packages/zowe-explorer/package.nls.json
  pnpm-lock.yaml
Labels: size/L

#3618 Fix a situation where hostname validation caused the host cannot be blank error to appear
  packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
  packages/zowe-explorer/src/utils/AuthUtils.ts
Labels: size/S

#3620 `datasets` -> `dataSets`, fix event not being disposed
  packages/zowe-explorer-api/__mocks__/vscode.ts
  packages/zowe-explorer-api/__tests__/__unit__/vscode/ui/TableView.unit.test.ts
  packages/zowe-explorer-api/__tests__/__unit__/vscode/ui/WebView.unit.test.ts
  packages/zowe-explorer-api/src/vscode/ui/WebView.ts
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/package.nls.json
  packages/zowe-explorer/src/configuration/Constants.ts
Labels: size/M

#3625 Fix duplicate nodes when adding profiles
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/profiles/ProfilesCache.unit.test.ts
  packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
Labels: size/S

#3624 refactor: Move `onProfileUpdated` to API register, preserve access through getters
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__mocks__/vscode.ts
  packages/zowe-explorer-api/__tests__/__unit__/vscode/ZoweVsCodeExtension.unit.test.ts
  packages/zowe-explorer-api/src/extend/IRegisterClient.ts
  packages/zowe-explorer-api/src/vscode/ZoweVsCodeExtension.ts
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__mocks__/vscode.ts
  packages/zowe-explorer/__tests__/__unit__/configuration/Profiles.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/extending/ZoweExplorerApiRegister.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedInit.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedUtils.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/UssFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/ZoweUSSNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/__snapshots__/ZoweUSSNode.unit.test.ts.snap
  packages/zowe-explorer/src/extending/ZoweExplorerApiRegister.ts
  packages/zowe-explorer/src/trees/shared/SharedInit.ts
  packages/zowe-explorer/src/trees/shared/SharedUtils.ts
Labels: size/L
