Repository zowe/zowe-explorer-vscode, pull requests merged in 2025-07, with the labels that each got.

#3728 fix: secure credentials as numbers or other types
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/package.json
  packages/zowe-explorer/package.nls.json
  packages/zowe-explorer/release-notes.md
  pnpm-lock.yaml
Labels: size/M

#3689 Extender workspace
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__mocks__/mockCreators/shared.ts
  packages/zowe-explorer/__tests__/__unit__/extension.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/shared/SharedInit.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/UssFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
  packages/zowe-explorer/package.json
  packages/zowe-explorer/package.nls.json
  packages/zowe-explorer/src/configuration/Constants.ts
  packages/zowe-explorer/src/extending/ZoweExplorerExtender.ts
  packages/zowe-explorer/src/extension.ts
  packages/zowe-explorer/src/trees/shared/SharedInit.ts
  packages/zowe-explorer/src/trees/uss/UssFSProvider.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
Labels: size/L

#3749 Fix/jobs pagination defaults
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/package.json
Labels: size/XS

#3740 Port 3.2.2 fixes
  lerna.json
  packages/eslint-plugin-zowe-explorer/CHANGELOG.md
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-api/__tests__/__unit__/fs/BaseProvider.unit.test.ts
  packages/zowe-explorer-api/__tests__/__unit__/profiles/ProfilesCache.unit.test.ts
  packages/zowe-explorer-api/__tests__/__unit__/tree/pagination.unit.test.ts
  packages/zowe-explorer-api/package.json
  packages/zowe-explorer-api/src/fs/utils/FsAbstractUtils.ts
  packages/zowe-explorer-api/src/profiles/ProfilesCache.ts
  packages/zowe-explorer-api/src/tree/ZoweTreeNode.ts
  packages/zowe-explorer-api/src/vscode/ZoweVsCodeExtension.ts
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/package.json
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__integration__/bdd/step_definitions/Settings.steps.ts
  packages/zowe-explorer/__tests__/__mocks__/@zowe/imperative.ts
  packages/zowe-explorer/__tests__/__unit__/commands/ZoweCommandProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/ZoweTreeProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/ZoweDatasetNode.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobActions.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobInit.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/job/JobTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/UssFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/utils/ProfilesUtils.unit.test.ts
  packages/zowe-explorer/l10n/poeditor.json
  packages/zowe-explorer/package.json
  packages/zowe-explorer/package.nls.json
  packages/zowe-explorer/src/extending/ZoweExplorerExtender.ts
  packages/zowe-explorer/src/trees/dataset/DatasetFSProvider.ts
  packages/zowe-explorer/src/trees/dataset/ZoweDatasetNode.ts
  packages/zowe-explorer/src/trees/job/ZoweJobNode.ts
  packages/zowe-explorer/src/trees/uss/USSInit.ts
  packages/zowe-explorer/src/trees/uss/UssFSProvider.ts
  packages/zowe-explorer/src/trees/uss/ZoweUSSNode.ts
  packages/zowe-explorer/src/utils/AuthUtils.ts
  packages/zowe-explorer/src/utils/ProfilesUtils.ts
  packages/zowe-explorer/src/webviews/package.json
  pnpm-lock.yaml
Labels: size/XXL

#3759 Port 3.2.2 updates
  packages/eslint-plugin-zowe-explorer/CHANGELOG.md
  packages/zowe-explorer-api/CHANGELOG.md
  packages/zowe-explorer-ftp-extension/CHANGELOG.md
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetFSProvider.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/UssFSProvider.unit.test.ts
  packages/zowe-explorer/l10n/poeditor.json
  pnpm-lock.yaml
Labels: no-changelog, size/M

#3767 Update dev deps to fix npm audit
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  pnpm-lock.yaml
Labels: no-changelog, size/XS

#3769 Prepare 2.18.2 release
  lerna.json
  packages/eslint-plugin-zowe-explorer/CHANGELOG.md
Labels: no-changelog, size/XS

#3768 feat: Submit user input and skip prompt for "Create a new filter" if provided
  packages/zowe-explorer/CHANGELOG.md
  packages/zowe-explorer/__tests__/__unit__/trees/dataset/DatasetTree.unit.test.ts
  packages/zowe-explorer/__tests__/__unit__/trees/uss/USSTree.unit.test.ts
  packages/zowe-explorer/src/trees/dataset/DatasetTree.ts
  packages/zowe-explorer/src/trees/uss/USSTree.ts
Labels: size/XL
